Documentation updates, fixes, centaurihelp --browse

diff --git a/library/_centauri_bash_ext b/library/_centauri_bash_ext
--- a/library/_centauri_bash_ext
+++ b/library/_centauri_bash_ext
@@ -1,6 +1,6 @@
 #!/bin/bash
 # ------------------------------------------------------------------------------
-# _centauri_bash_ext = Centauri Bash Library Sort and IO Extension
+# _centauri_bash_ext = centauri-bash-lib: Filesystem extension
 #
 # Call:     . _centauri_bash_ext
 #
@@ -26,9 +26,7 @@ CEN_MODULES["_centauri_bash_ext"]="0.22:1"
 CEN_EXT_TEMP=               # temp file base path, see tmpfile
 CEN_EXT_TIDX=               # ... auto index
 CEN_EXT_TPID=               # ... subshell pid
-CEN_EXT_QUIT=               # hook, see tmpfile
 CEN_EXT_REALP=              # 0:=use external  1:=use realpath builtin
-
 
 # ------------------------------------------------------------------------------
 # get logical path (into <logi>): [-e] [-e] <logi> <path>
@@ -1003,9 +1001,9 @@ remove() {
     elif [ $# = 0 ] ; then
         return 0
     else                                        # use coreutils remove
-        _oitm=$"files/folders"
+        _oitm=$"entries"
     fi
-    $_omsg -a -p $"Removing %s: %s" "$_oitm" "$*"
+    $_omsg -a -c " $_oitm" -- "$*"
 
     # bash builtins might be unable to handle options or --
     if [ -n "$_oone" ] ; then
@@ -1085,7 +1083,7 @@ rename() {
         fi
     fi
 
-    $_omsg -a -p $"Renaming '%s' to '%s'" "$1" "$_dest"
+    $_omsg -a -c " " -- "$1 => $_dest"
     sysrun -b $_orun $_osys -- mv -f -- "$1" "$_dest" && return 0
     [ -n "$CEN_OPT_DRYRUN" ]                     # --dryrun always returns 0
 }
@@ -1172,7 +1170,7 @@ resolve() {
     # get executable - use _centauri_bash_lib paths and resolve argv0 if needed
     if [ -n "$_oexe" ] ; then
         local _logi _self="$CEN_TOOLS:$CEN_LIBRARY:${BASH_ARGV0%/*}"
-        PATH="$PATH:$_self" sysrun -q -r -s -a _logi -- type -f -p -- "$1"
+        PATH="$PATH:$_self" sysrun -q -r -a _logi -- type -f -p -- "$1"
         if [ -z "$_logi" ] ; then
             [ -h "$BASH_ARGV0" ] && _cen_path_realp -c "$BASH_ARGV0"
             _self="${_logi%/*}"
@@ -1236,22 +1234,23 @@ resolve() {
 }
 
 # ------------------------------------------------------------------------------
-# splitcall - run commands or funtions splitting long arguments lists
+# splitcall - run commands or functions splitting long arguments lists
 #
-# Call:     splitcall -c|-s <what> [-e|-f|-q] [-p] [-r]
+# Call:     splitcall -c|-s <what> [-e|-f|-q] [-g <good>] [-p] [-r]
 #           °         <>           [-a <para>] [-m <maxi>] [-d <deli>] -i <data>
-#           splitcall -c|-s <what> [-e|-f|-q] [-r]
+#           splitcall -c|-s <what> [-e|-f|-q] [-g <good>] [-r]
 #           °         <>           [-a <para>] [-m <maxi>] [-p] [-d <deli>] -- <arg>...
 #
-#           ***not yet implented***
+#           ***implentation is incomplete***
 #
 # Options:  -a  parameter array, see below
 #           -c  call a script function
 #           -d  delimiter passed to [[splitjoin()]]
 #           -e  add option -e (report errors)
 #           -f  add option -f (make errors fatal)
+#           -g  stop processing if exit code of <what> is greater <good>
 #           -i  input variable name (can be an array)
-#           -m  maximum chunk size or parallel processes
+#           -m  maximum chunk size for parallel processes
 #           -p  parallel processing, see below
 #           -q  add option -q (no messages)
 #           -r  add option -r (ignore --dryrun)
@@ -1259,7 +1258,9 @@ resolve() {
 #
 # Arguments:<arg>   list of fields that get added to <data>
 #           <data>  list to be split into chunks
-#           <func>  a function to be invoked for chunks of <data>
+#           <deli>  used to split strings into items, see [[splitjoin()]]
+#           <good>  maximum non-error return code (default is using "error°-t")
+#           <what>  a function/command to be invoked for chunks of <data>
 #           <para>  parameters passed to <func>, can be string or array, '@'
 #           °       stands for a chunk of <data>. If no '@' field is passed,
 #           °       it automatically gets appended to <para>.
@@ -1282,27 +1283,75 @@ resolve() {
 #.          splitcall -p -c "wrapper" -e -r -- '1.dat' '2.dat' '3.dat'
 # ------------------------------------------------------------------------------
 splitcall() {
-    local _oerr _vnam _call _deli _fdry _ivar _maxi _ppar _srun
+    local _oerr _vnam _call _deli _fdry _fpre _good _ivar _maxi _ppar _srun
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -a)   shift ; _vnam="$1" ;;
-      -c)   shift ; _call="$1" ;;
+      -c)   shift ; _call="$1" ; isfunction -f -- "$1" ;;
       -d)   shift ; _deli="$1" ;;
-      -e)   _oerr='-e' ;;
-      -f)   _oerr='-f' ;;
+      -e)   _oerr='-e' ; _fpre='-p' ;;
+      -f)   _oerr='-f' ; _fpre='-p' ;;
+      -g)   shift ; _good="$1" ;;
       -i)   shift ; _ivar="$1" ;;
       -m)   shift ; _maxi="$1" ;;
       -p)   _ppar=1 ;;
       -q)   _oerr='-q' ;;
       -r)   _fdry='-r' ;;
-      -s)   shift ; _srun="$1" ;;
+      -s)   shift ; local _cen_splitcall
+            sysfind -f -s _cen_splitcall -- "$1" ; _srun="$_cen_splitcall" ;;
       *)    _cen_abort - "$1"
       esac ; shift
     done
     [ -z "$_call" -a -z "$_srun" ] && _cen_abort = '-c|-s'
-    [ -n "$1" ] && _cen_abort - "$1"
-    fatal -t "Not yet implented"
+
+    local _offs= _leng _coun="$#" _aidx _args _stat _save _savd _rval=0
+    _leng="${_maxi:-1024}"
+
+    if [ -n "$_vnam" ] ; then                       # find '@' in param list
+        listsearch -c -n _aidx -i "$_vnam" -- '@' ||
+            _cen_abort $"No '@' in arguments array:" '-a'
+        local -n _cen_splitcall="$_vnam"
+    fi
+
+    [ -n "$_ppar" ] && fatal -t "Not yet implented:" '-p'
+    [ -n "$_deli" ] && fatal -t "Not yet implented:" '-d'
+    [ -n "$_ivar" ] && fatal -t "Not yet implented:" '-i'
+
+    if [ "${_good:--}" = '-' ] ; then               # save/reset error state
+        _save="$CEN_ERROR" ; _savd="$CEN_DONE"
+        error -c
+    fi
+
+    while [[ "$_offs" -lt "$_coun" ]] ; do
+        if [ -n "$_vnam" ] ; then                   # make argument list
+            _args=("${_cen_splitcall[@]::_aidx}")
+            _args+=("${@:_offs+1:_leng}")
+            _args+=("${_cen_splitcall[@]:_aidx+1}")
+        else
+            _args=("${@:_offs+1:_leng}")
+        fi
+
+        if [ -n "$_srun" ] ; then
+            sysrun -n $_fdry $_fpre $_oerr -- "$_srun" "${_args[@]}"
+        else
+            $_call $_fdry $_oerr "${_args[@]}"
+        fi
+        _stat="$?" ; ((_offs+=_leng))
+        [ "$_stat" = 0 ] && continue
+
+        if [ "${_good:--}" = '-' ] ; then           # stop after any error
+            error -t && continue
+        elif [ "$_stat" -le "${_good:-0}" ] ; then  # stop if $? > _good
+            continue
+        fi
+        _rval="$_stat" ; break                      # stop with error code
+    done || :
+
+    if [ "${_good:--}" = '-' -a "$CEN_ERROR" = '0' ] ; then
+        CEN_ERROR="$_save" ; CEN_DONE="$_savd"      # restore error state
+    fi
+    return $_rval
 }
 
 # ------------------------------------------------------------------------------
@@ -1617,14 +1666,14 @@ symlink() {
             [ -n "$_fign" ] && _oftl="$_mesg"
             $_oftl $"Link target does not exist:" "$_targ" ; return 1
         elif [ "$_targ" -ef "$_link" ] ; then
-            $_mesg -a $"Target '$_targ', link is current"": $_link" ; return 0
+            $_mesg -a -c $" valid" -- "$_link => $_targ" ; return 0
         else
             [ -n "$_ocan" ] && _cen_path_realp -c "$_targ" && _targ="$_logi"
         fi
 
         if [ -h "$_link" ] ; then
-            $_mesg -a $"Removing existing link"": $_link"
             remove -s -- "$_link" || return 2
+            $_mesg -a -c $" removed" -- "$_link"
         elif [ -e "$_link" ] ; then
             if [ "$_move" = 0 ] ; then
                 remove -d -s -- "$_link" || return 2
@@ -1647,7 +1696,8 @@ symlink() {
     else
         sysrun $_osys -b -m "$_etxt" -d -- ln $_onck -s "$_targ" "$_link" || return 1
     fi
-    $_mesg -a -p $"Target '%s', created link '%s'" "$_targ" "$_link" ; return 0
+   # $_mesg -a -p $"Target '%s', created link '%s'" "$_targ" "$_link" ; return 0
+    $_mesg -a -c $" created" -- "$_link => $_targ" ; return 0
 }
 
 # ------------------------------------------------------------------------------
@@ -1746,7 +1796,7 @@ symlink() {
 # ------------------------------------------------------------------------------
 sysrun() {
     $CEN_NOTRACE set +x
-    local _ecmd="$CEN_TRACE" _emsg _ofmt _oign _osta _opre _orun _oout _owho _ffnd=1 _vnam
+    local _ecmd="$CEN_TRACE" _emsg _ofmt _oign _osta _opre _orun _oout _owho _fqui _ffnd=1 _vnam
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
@@ -1760,7 +1810,7 @@ sysrun() {
       -m)   shift ; _emsg="$1" ; [ -z "$_oout" ] && _oout=0 ;;
       -n)   _ffnd= ;;
       -p)   _ofmt=1 ; [ -z "$_oout" ] && _oout=0 ;;
-      -q)   [ -z "$_oout" ] && _oout=0 ;;
+      -q)   _fqui=1 ; [ -z "$_oout" ] && _oout=0 ;;
       -r)   _orun="-r" ;;
 #      -s)   ;;
       -w)   shift ; _owho="$1" ;;
@@ -1852,6 +1902,7 @@ sysrun() {
 
     # error reporting ...
     [ -z "$_osta" ] && _osta=1                  # must have a value here
+    [ -n "$_fqui" ] && return $_osta
     case "$_osta" in
     0)      $CEN_NOTRACE set -x ; return 0 ;;
     1)      ;;
@@ -1867,7 +1918,7 @@ sysrun() {
 
     [ "${_emsg:--}" = '-' ] && _emsg=$"Running '%s%s' failed"
     [ -n "$_xmsg" ] && _xmsg=": $_xmsg"
-    if [ -z "$_ecmd" -a -n "$_ofmt" ] ; then            # system -p style
+    if [ "$_ecmd" = "$CEN_TRACE" -a -n "$_ofmt" ] ; then    # system -p style
         splitjoin -j _xtmp -d '\n' -i "${_vnam:-_xerr}"
         message -m "$_xtmp"
         $CEN_NOTRACE set -x ; return $_osta
@@ -1877,10 +1928,10 @@ sysrun() {
         for _xtmp in "${_xtmp[@]}" ; do
             _xarg+="${_xtmp#/*: *: }"$'\n'              # strip bash error prefix
         done
-        $_ecmd -m -p "${_emsg} %s\n%s" "${_owho:-($_xcmd)}" "" "$_xmsg" "$_xarg"
+        [ "$_xcmd" = 'builtin' ] && _xtmp=" $1" || _xtmp=
+        $_ecmd -m -p "${_emsg} %s\n%s" "${_owho:-($_xcmd)}" "$_xtmp" "$_xmsg" "$_xarg"
     else                                                # simple ...
-        # [ $# -gt 0 ] && _xarg=" $*"
-        $_ecmd -p "$_emsg$_xmsg" "${_owho:-($_xcmd)}" "$_xarg"
+        $_ecmd -p "$_emsg$_xmsg" "${_owho:-($_xcmd)}" "$_xtmp"
     fi
     $CEN_NOTRACE set -x ; return $_osta
 }
@@ -2011,7 +2062,7 @@ tmpfile() {
         if [ -z "$_odel" ] ; then
             if [ -n "$CEN_EXT_TEMP" ] ; then
                 _updt="${CEN_EXT_TEMP%/*}"
-                [ "$_updt" = "$_base" ] || $CEN_TRACE2 "tmpfile: update $_updt -> $_base"
+                [ "$_updt" = "$_base" ] || $CEN_TRACE2 -c $" update" -- "$_updt => $_base"
             fi
             folder $_oftl $_orun -m -s _base -- "$_base" 700 || return 1
         fi
@@ -2025,18 +2076,17 @@ tmpfile() {
 
     if [ -n "$_odel" ] ; then
         [ -z "$_base" ] && return 0                     # not initialized
-        $CEN_TRACE2 "tmpfile: remove $_base$_ssuf*"
+        $CEN_TRACE2 -c $" remove" -- "$_base$_ssuf*"
         CEN_EXT_TEMP= ; CEN_TMPFILE=
         [ -d "$_base" ] && return 0                     # don't remove folder
         set +f ; set -- "$_base$_ssuf"*                 # make sure glob is on
         [ "$1" = "$_base$_ssuf*" ] && return 0          # nothing to remove
-        sysrun -q -b -- rm -f -- "$@" ; return          # return status
+        sysrun $_orun -q -b -- rm -f -- "$@" ; return   # return status
     fi
 
     # create folder / file
 
     if [ -z "$CEN_EXT_TEMP" ] ; then                    # create folder, set hook
-        context -h _cen_ext_quit CEN_EXT_QUIT
         CEN_EXT_TEMP="$_base"
     fi
     [ -n "$_onoc" -a -z "$_snam" ] && return 0          # init only
@@ -2280,11 +2330,10 @@ walk() {
 # Startup - module init
 # ------------------------------------------------------------------------------
 
-# hook to delete temp files created by tmpfile
+# delete temp files created by tmpfile
 _cen_ext_quit() {
-    $CEN_NOTRACE set +x ; tmpfile -d ; $CEN_NOTRACE set -x
-    $CEN_EXT_QUIT "$@"
-} || :
+    [ "$CEN_EXT_TEMP" ] && tmpfile -d -r
+}
 
 :
 # end
diff --git a/library/_centauri_bash_pro b/library/_centauri_bash_pro
--- a/library/_centauri_bash_pro
+++ b/library/_centauri_bash_pro
@@ -1,6 +1,6 @@
 #!/bin/bash
 # ------------------------------------------------------------------------------
-# _centauri_bash_pro = Centauri Bash Library Progress Display Support
+# _centauri_bash_pro = centauri-bash-lib: Progress display support
 #
 # Call:     . _centauri_bash_pro
 #
@@ -17,10 +17,12 @@
 # Copyright Dr. J. Pfennig (c) 2022
 # ------------------------------------------------------------------------------
 
-CEN_MODULES["_centauri_bash_pro"]="0.01:1"
+CEN_MODULES["_centauri_bash_pro"]="0.02:1"
 
 # CEN_CONSOLE           # imported ...
 # CEN_WINDOWS
+
+CEN_PROGRESS=           # 0:disabled  1:enbabled  2:active
 
 # ------------------------------------------------------------------------------
 # progress - progress bar or incremental progress reporting
@@ -147,9 +149,11 @@ CEN_MODULES["_centauri_bash_pro"]="0.01:1"
 #
 # ------------------------------------------------------------------------------
 progress() {
+    # default is -e (remove progress message/window)
+    [ $# = 0 ] && _fend=0
 
     # parse options
-    local _prog _fdel _fend _flin _find _ftxt _foff _step _work _stat=0 _aind="$CEN_AUTOIND"
+    local _prog _fdel _fend _flin _find _ftxt _step _work _stat=0 _aind="$CEN_AUTOIND"
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       -)    break ;;
@@ -163,7 +167,7 @@ progress() {
       -p)   _ftxt=2 ;;
       -s)   shift ; _step="$1" ;;
       -t)   _ftxt=1 ;;
-      -v)   [ "$CEN_VERB" -gt 1 ] && _foff=1 ;;
+      -v)   [ "$CEN_VERB" -gt 1 ] && CEN_PROGRESS=0 ;;
       -w)   shift ; _work="$1" ;;
       *)    _cen_abort - "$1"
       esac ; shift
@@ -171,35 +175,43 @@ progress() {
 
     # get console / windows status, init console mode
 
-    if [ -z "$CEN_CONSOLE" ] ; then             # console() has not run
-        if [ "$CEN_OPT_GUI" = 0 ] ; then        # disables auto-init
-            _foff=   # 1
+    if [ -z "$CEN_PROGRESS" ] ; then            # not yet initialized
+        if [ -n "$CEN_PAGER" -o "$CEN_VERB" -lt 1 -o "$CEN_CONSOLE" = 0 ] ; then
+            # disable for --quiet or output not to console
+            CEN_PROGRESS=0                      # no error return!
+        elif [ "$CEN_OPT_GUI" = 0 ] ; then      # disables auto-init
+            _stat=1
+            trace -c ' disabled' "option --gui=0"
         elif [ -z "${CEN_MODULES["_centauri_bash_win"]}" ] ; then
             console || _stat=$?
         elif [ -z "$CEN_WINDOWS" ] ; then       # _centauri_bash_win is loaded
             windows || _stat=$?                 # must run windows()
         fi
-        if [ -n "$_work" ] ; then               # must always run
-            :
-        elif [ "$_stat" != 0 ] ; then           # failed to init
-            return $_stat
-        elif [ -n "$CEN_WINDOWS" ] ; then       # foreward to _centauri_bash_win
-            _cen_win_prog "$_prog" "$_fdel" "$_fend" "$_flin" "$_step" "$_ftxt" "$@" || _stat=$?
-            return $_stat
+
+        if [ "$_stat" != 0 ] ; then             # failed to init
+            CEN_PROGRESS=0
+            [ -z "$_work" ] && return $_stat    # worker must always run
         fi
     fi
 
-    # disable for --quiet or output not to console
-    [ -n "$CEN_PAGER" ] && _foff=1
-    [ "${CEN_CONSOLE:-1}" = 0 ] && _foff=1
+    # flag open progress message / window
+    if [ "$CEN_PROGRESS" != 0 ] ;then
+        [ -z "$_fend" ] && CEN_PROGRESS=2 || CEN_PROGRESS=1
+    fi
+    [ "$_fend" = 0 ] && _fend=
 
+    # run worker (always) or progress implementation
     if [ -n "$_work" ] ; then                   # worker mode
         local _mini="${_step#*:}" ; [ "$_mini" = "$_step" ] && _mini=1
-        [ -n "$_foff" ] && _mini=0
+        [ "$CEN_PROGRESS" = 0 ] && _mini=0
         _cen_pro_work "$_work" "$_fdel" "${_step%:*}" "$_mini" "$_prog" "$@" || _stat=$?
-    elif [ -z "$_foff" ] ; then
-         _cen_con_prog "$_prog" "$_fend" "$_flin" "$_find" "$_step" "$_ftxt" "$@" || _stat=$?
-        [ -n "$_fdel" ] && sleep "$_fdel"
+    elif [ "$CEN_PROGRESS" != 0 ] ; then
+        if [ -n "$CEN_WINDOWS" ] ; then         # foreward to _centauri_bash_win
+            _cen_win_prog "$_prog" "$_fdel" "$_fend" "$_flin" "$_step" "$_ftxt" "$@" || _stat=$?
+        else
+            _cen_con_prog "$_prog" "$_fend" "$_flin" "$_find" "$_step" "$_ftxt" "$@" || _stat=$?
+            [ -n "$_fdel" ] && sleep "$_fdel"
+        fi
     fi
     return "$_stat"
 }
@@ -261,6 +273,13 @@ _cen_pro_work() {
     [ -n "$_fdel" ] && sleep "$_fdel"
     [ -n "$CEN_CONSOLE" ] && context -t -       # reset trap handler
     return "$_stat"
+}
+
+# ------------------------------------------------------------------------------
+# quit callback to cancel progress()
+# ------------------------------------------------------------------------------
+_cen_pro_quit() {
+    [ "${CEN_PROGRESS:-0}" -gt 1 ] && progress  # remove progress message/window
 }
 
 :
diff --git a/library/_centauri_bash_xml b/library/_centauri_bash_xml
--- a/library/_centauri_bash_xml
+++ b/library/_centauri_bash_xml
@@ -1,6 +1,6 @@
 #!/bin/bash
 # ------------------------------------------------------------------------------
-# _centauri_bash_xml = Centauri Bash Library XML/HTML Support
+# _centauri_bash_xml = centauri-bash-lib: Support for generating XML/HTML
 #
 # Call:     . _centauri_bash_xml
 #
@@ -24,6 +24,7 @@
 CEN_MODULES["_centauri_bash_xml"]="0.20:1"
 
 CEN_XML_BUFFER=
+CEN_XML_ERROR=          # error flag
 CEN_XML_HTML=           # HTML version
 CEN_XML_INDENT=
 CEN_XML_DOCNODE=        # root node -- or "-"  -- or empty
@@ -255,8 +256,9 @@ xml_document() {
 
     # initialize output
     if [ -n "$_optb" ] ; then
-        if [ "${_oout:--}" = '-' ] ; then
-            CEN_XML_OUTPUT=
+        CEN_XML_ERROR=
+        if [ "${_oout:--}" = '-' -o "$_oout" = '/dev/stdout' ] ; then
+            CEN_XML_OUTPUT=1
         elif [ "$_oout" = '+' ] ; then
             CEN_XML_OUTPUT='+'
         elif [ -z "${_oout//[0-9]/}" ] ; then
@@ -337,7 +339,7 @@ xml_document() {
             xml_element "$CEN_XML_DOCNODE" -e -u
         fi
         xml_flush -n
-        [ "${CEN_XML_OUTPUT:-+}" = '+' ] || redirect -s -v CEN_XML_OUTPUT
+        [ -n "${CEN_XML_OUTPUT/[+12]/}" ] && redirect -s -v CEN_XML_OUTPUT
     fi
 }
 
@@ -548,6 +550,7 @@ xml_flush() {
     # reset state
     if [ -n "$_ores" ] ; then
         CEN_XML_BUFFER=
+        CEN_XML_ERROR=
         CEN_XML_HTML=
         CEN_XML_INDENT=
         CEN_XML_DOCNODE=
@@ -557,11 +560,14 @@ xml_flush() {
         CEN_XML_ARGS=() ; CEN_XML_ATTR=()
     fi
 
+    if [ -n "$CEN_XML_ERROR" ] ; then           # ignore after write error
+        CEN_XML_BUFFER= ; return 1
+    fi
     [ -n "$_over" ] && CEN_XML_HTML="$_over"
     [ -z "$CEN_XML_OUTPUT" ] && CEN_XML_OUTPUT="$_ohan"
 
     # right trim
-    [ -z "$CEN_XML_BUFFER" ] && return
+    [ -z "$CEN_XML_BUFFER" ] && return 0
     local _blen="${#CEN_XML_BUFFER}"
     while [ "$_blen" -gt 0 ] ; do
         [ "${CEN_XML_BUFFER:_blen-1:1}" = ' ' ] || break
@@ -586,10 +592,13 @@ xml_flush() {
             CEN_XML_BUFFER="${CEN_XML_BUFFER::_blen}"
             [ "$CEN_XML_FORMAT" = "1" ] && CEN_XML_BUFFER+="$CEN_XML_INDENT"
             return 0
-        elif [ "$_ohan" = '-' ] ; then          # send to stdout
-            printf '%s' "${CEN_XML_BUFFER::_blen}"
+        elif [ "$_ohan" = 1 ] ; then            # send to stdout
+            printf '%s' "${CEN_XML_BUFFER::_blen}" 2>/dev/null
         else
             printf '%s' "${CEN_XML_BUFFER::_blen}" >&$_ohan
+        fi
+        if [ $? != 0 ] ; then
+            CEN_XML_ERROR=1 ; $CEN_TRACE -c " error" "write failed" ; return 1
         fi
     fi
 
@@ -598,6 +607,7 @@ xml_flush() {
     else
         CEN_XML_BUFFER=
     fi
+    return 0
 }
 
 # ------------------------------------------------------------------------------
diff --git a/tools/centaurilauncher b/tools/centaurilauncher
--- a/tools/centaurilauncher
+++ b/tools/centaurilauncher
@@ -97,7 +97,7 @@ launcher_html() {
         -f|-q)  oerr="$1" ;;
         -m)     shift ; mode="$1" ;;
         -o|-t)  shift ;;
-        -x)     ochk=1 ;;
+        -x)    return 0 ;; #### ochk=1 ;;
         *)
         esac ; shift
     done
@@ -112,7 +112,7 @@ launcher_html() {
         error -p $"Only one argument allowed (%s): %s" "${appl##*/}" "$*" ; return 1
     fi
 
-    # use --- to skip everything before
+    # skip command options, use --- to skip everything before
     if listsearch -c -n indx -- '---' "$@" ; then
         trace "found --- $indx +" "${@:1:indx}" + "${@:indx+2}"
         args=("${@:1:indx}") ; shift $((indx+1))
@@ -126,9 +126,22 @@ launcher_html() {
             esac ; shift
         done
     fi
+    # the remaining args should be html files or urls
 
-    if [ "$1" != '-' ] ; then
-        application_url "$1" || return 1
+    # search url/file list backwards until an existing file is found
+    local _coun="$#" _indx _strt
+    while ((_coun--)) ; do
+        _indx=$((_coun + 1))
+        _strt="${!_indx}"
+        case "$_strt" in
+            /*)     [ -s "${_strt%#*}" ] && break || _strt= ;;
+            *)      break                       # not a file, use this url
+        esac
+    done
+
+
+    if [ "${_strt:--}" != '-' ] ; then
+        application_url "$_strt" || return 1
         trace "html url:" "$DAT_URL"
         args+=("$DAT_URL")
     fi
@@ -310,13 +323,13 @@ server.modules += ( "mod_cgi" )
 # ------------------------------------------------------------------------------
 launcher_qmlweb() {
 $CEN_DEBUG -c -- "$@"
-    local oerr mode orun _ainf _titl
+    local oerr orun _mode _ainf _titl
     while [ $# -gt 0 ] ; do
         case "$1" in
         --)   shift ; break ;;
         -f)   oerr='-f' ;;
         -i)   shift ; splitjoin -s _ainf -d ':' -- "$1" ;; # _oinf="$1" ;;
-        -m)   shift ; mode="$1" ;;
+        -m)   shift ; _mode="$1" ;;
         -q)   oerr='-q' ;;
         -r)   orun='-r' ;;
         -t)   shift ; _titl="$1" ;;
@@ -326,33 +339,42 @@ $CEN_DEBUG -c -- "$@"
 
     $CEN_DEBUG -c -- "$*"
     local _pqml="$1" _titl ; shift
-    local _file _resx="${1:--}" _resy="${2:--}" _zoom="${3:--}" _strt="$4"
-    [ "$_resx" = '-' ] && _resx=1024
-    [ "$_resy" = '-' ] && _resy=768
-    [ "$_zoom" = '-' ] && _zoom=1
-   # if [ "${_oinf:--}" != '-' ] ; then
-   #     local _ainf
-   #     splitjoin -s _ainf -d ':' -i _oinf
-        [ "${_ainf[0]:--}" != '-' ] && _resx="${_ainf[0]}"
-        [ "${_ainf[1]:--}" != '-' ] && _resy="${_ainf[1]}"
-        [ "${_ainf[2]:--}" != '-' ] && _zoom="${_ainf[2]}"
-   # fi
+    local _file _resx="${1:--}" _resy="${2:--}" _zoom="${3:--}"
+    shift ; shift ; shift
 
+    # search url/file list backwards until an existing file is found
+    local _coun="$#" _indx _strt
+    while ((_coun--)) ; do
+        _indx=$((_coun + 1))
+        _strt="${!_indx}"
+        case "$_strt" in
+            /*)     [ -s "${_strt%#*}" ] && break || _strt= ;;
+            *)      break                       # not a file, use this url
+        esac
+    done
+
+    # qml window geometry
+    [ "${_ainf[0]:--}" != '-' ] && _resx="${_ainf[0]}"
+    [ "${_ainf[1]:--}" != '-' ] && _resy="${_ainf[1]}"
+    [ "${_ainf[2]:--}" != '-' ] && _zoom="${_ainf[2]}"
+    [ "$_resx" = '-' ] && _resx='(Screen.desktopAvailableWidth * 6) / 10'
+    [ "$_resy" = '-' ] && _resy='(Screen.desktopAvailableHeight * 4) / 5'
+    [ "$_zoom" = '-' ] && _zoom='Screen.pixelDensity / 4.5'
     if [ "${_titl:--}" = '-' ] ; then
         _titl="$CEN_NAME"
         [ -n "$CEN_EMBED" ] && _titl="$CEN_EMBED ⸺ $CEN_NAME"
     fi
 
-    local qvar='Q''t'                           # hide to avoid mime type qml
+    local _qvar='Q''t' _pipe                        # hide Qt to avoid mime type qml
     tmpfile -n -s _file -- "launcher.qml" || return 1
 
     # wait for synchronization pipe - see 'launcher_webapp'
     if [ -n "$DAT_SYNCPIPE" ] ; then
-        local _mode _wurl _dumy
+        local _flag _wurl _dumy
         trace -a $"wait for synchronization:" "$DAT_SYNCPIPE"
-        read -t 60 -u "$DAT_SYNCPIPE" _mode _wurl _dumy || return 1
-        trace -a $"synchronization message :" "$_mode" "$_wurl"
-        [ "$_mode" = 'OK' ] || return 1
+        read -t 60 -u "$DAT_SYNCPIPE" _flag _wurl _dumy || return 1
+        trace -a $"synchronization message :" "$_flag" "$_wurl"
+        [ "$_flag" = 'OK' ] || return 1
         if [ "${_wurl:--}" != '-' ] ; then
             DAT_URL= ; _strt="$_wurl"
         fi
@@ -362,29 +384,43 @@ $CEN_DEBUG -c -- "$@"
         trace -a $"generate config for qml :" "$_strt"
         application_url "$_strt" || return 1
     fi
-    trace $"qml web url:" "$DAT_URL"
+    trace -c $"qml web url" -- "$DAT_URL"
     create -r -t -c -- "$_file" 400 <<!EOF || return 1
- import ${qvar}Quick 2.0
- import ${qvar}Quick.Window 2.0
- import ${qvar}WebEngine 1.1
- Window {
-    width: $_resx
-    height: $_resy
+import ${_qvar}Quick 2.0
+import ${_qvar}Quick.Window 2.0
+import ${_qvar}WebEngine 1.2
+Window {
+    function cen_posx() { return (Screen.desktopAvailableWidth - $_resx) / 2; }
+    function cen_posy() { return (Screen.desktopAvailableHeight - $_resy) / 2; }
+    x: cen_posx() ; y: cen_posy()
+    width: $_resx ; height: $_resy
     visible: true
     title: "$_titl"
+
     WebEngineView {
-        zoomFactor: $_zoom
         anchors.fill: parent
         url: "$DAT_URL"
+        focus: true
+        zoomFactor: $_zoom
+        onJavaScriptConsoleMessage: {
+            if (message == 'QUIT') Qt.quit();
+            console.log(message);
+        }
    }
 }
 !EOF
 
-
-### rename to runcommand and document
-        launcher -x $oerr $orun -m "$mode" -- "$_pqml" --quiet "$_file"
-### TODO put this into runcommand
-        [ "${mode:-0}" = 0 ] || sleep 1
+    case "$_mode" in
+    # mode 1 makes no sense with qml, use mode=0
+    0|1)
+        launcher -x $oerr $orun -m 0 -- "$_pqml" --quiet "$_file" ;;
+    # for mode 2,3 we must wait until qml has read the script file. A pipe as
+    # dummy input file can be used for synchronization ...
+    *)
+        tmpfile -p -s _pipe 'pipe.qml'          # dummy input for qml
+        launcher -x $oerr $orun -m "$_mode" -- "$_pqml" --quiet "$_file" "$_pipe" &&
+            echo 2>/dev/null > "$_pipe"         # this is a blocking write
+    esac
     return 0
 }
 
@@ -642,7 +678,7 @@ actions() {
                     list+=("$1") ;;
             -i|-m|-o|-t|-y)                     # known value options ...
                     list+=("$1" "$2") ; shift ;;
-            *)      fatal $"Option '%s' is invalid (action '%s')" ;;
+            *)      fatal -p $"Option '%s' is invalid (action '%s')" "$1" "$CEN_ACTION" ;;
             esac ; shift
         done
 
