Minor changes and fixes

diff --git a/library/_centauri_bash_ext b/library/_centauri_bash_ext
--- a/library/_centauri_bash_ext
+++ b/library/_centauri_bash_ext
@@ -139,11 +139,11 @@ _cen_path_ltrim() {
 }
 
 # ------------------------------------------------------------------------------
-# Get full path, canonicalize, read link: -a|-c|-l <path>
+# Get full path, canonicalize, read link: -a|-c|-l <path>           (sets _logi)
 # ------------------------------------------------------------------------------
 _cen_path_realp() {
     local _exro _retr _rslt _opta
-
+    _logi=
     case "$CEN_EXT_REALP$1" in
 
     # run commands or builins
@@ -153,7 +153,7 @@ _cen_path_realp() {
     0-c)    _exro+=(readlink -m) ;;
     1-c)    _exro+=(realpath) ; _opta=1 ; _retr=1  ;;   # fails for all invalid links
 
-    ?-l)    [ -e "$2" ] && _exro+=(readlink) || _exro+=(readlink -m) ;;
+    ?-l)    [ -e "$2" ] || return 1 ; _exro+=(readlink) ;; # || _exro+=(readlink -m) ;;
 
     # check if builtin can be loaded
     -*)     CEN_EXT_REALP=0
@@ -181,11 +181,8 @@ _cen_path_realp() {
         sysrun -q -r -a _rslt -b -- readlink -m -- "$2" && _retr=0
     fi
 
-    if [ "$_retr" = 0 ] ; then                  # success: set _logi
-        _logi="$_rslt" ; return 0
-    else                                        # failure: clear _logi
-        _logi= ; return 1
-    fi
+    [ "$_retr" = 0 ] || return 1
+    _logi="$_rslt" ; return 0
 }
 
 # ------------------------------------------------------------------------------
@@ -275,7 +272,8 @@ attributes() {
 #
 # Options:  -a  recurse/archive (**/usr/bin/cp -a**)
 #           -f  make errors fatal
-#           -o  try ''copy-on-write'' (**/usr/bin/cp** --reflink=auto)
+#           -n  disable ''copy-on-write'' (**/usr/bin/cp** --reflink=never)
+#           -o  enable  ''copy-on-write'' (**/usr/bin/cp** --reflink=auto)
 #           -q  do not report errors
 #           -r  ignore --dryrun
 #           -s  no trace messages
@@ -287,16 +285,19 @@ attributes() {
 #
 #+This is a conviniency wrapper for coreutils **/usr/bin/cp** that provides some
 # extra reporting and error handling.
+#
+#+In newer versions for gnu coreutils ''copy-on-write'' is enabled by default.
 # ------------------------------------------------------------------------------
 copy() {
-    local _oerr="-e -p" _omsg="$CEN_TRACE" _oarc _ocow _oflg _oupd _olis _odes _orem
+    local _oflg='-e -p' _oerr='error' _omsg="$CEN_TRACE" _oarc _ocow _oupd _olis _odes _orem
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -a)   _oarc="-a" ;;
-      -f)   _oerr="-f -p" ; _oflg="-f" ;;
+      -f)   _oerr='fatal' ; _oflg='-f -p' ;;
+      -n)   _ocow="--reflink=never" ;;
       -o)   _ocow="--reflink=auto" ;;
-      -q)   _oerr="-q" ; _oflg="-q" ;;
+      -q)   _oerr="$CEN_TRACE" ; _oflg='-q' ;;
       -r)   _orun="-r" ;;
       -s)   _omsg=: ;;
       -u)   _oupd="-u" ;;
@@ -312,19 +313,26 @@ copy() {
     else
         _olis=("${@:1:$#-1}") ; _odes="${@:$#}"
         if [ ! -d "$_odes" ] ; then
-            $_omsg $"Copy destination is not a folder"": $_odes" ; return 2
+            $_oerr $"Copy destination is not a folder"": $_odes" ; return 2
         fi
     fi
-    if [ -n "$_orem" ] && [ -e "$_odes" ] ; then
-        $_omsg -a $"Removing destination before copy"": $_odes"
-        remove $_orun $_oflg -d -- "$_odes" || return 1     # may use builtins
+
+    if [ -e "$_odes" ] ; then
+        if [ -n "$_orem" ] ; then
+            $_omsg -a $"Removing destination before copy"": $_odes"
+            remove $_orun ${_oflg/-p/} -d -- "$_odes" || return 1
+        elif [ ! -w "$_odes" ] ; then
+            $_oerr $"Copy destination is not a writable"": $_odes" ; return 1
+        fi
     fi
+
     if [ $# -gt 2 ] ; then
-        $_omsg -a -p $"Copying %d item(s) to '%s'" "${#_olis[*]}" "$_odes"
+        $_omsg -a -p $"Copying %d item to '%s'" "${#_olis[*]}" "$_odes"
     else
         $_omsg -a -p $"Copying '%s' to '%s'" "${_olis[*]}" "$_odes"
     fi
-    sysrun $_oerr $_orun -b -- cp $_oarc $_ocow $_oupd -- "${_olis[@]}" "$_odes" && return 0
+    sysrun $_oflg $_orun -b -w 'copy()' -- \
+           cp $_oarc $_ocow $_oupd -- "${_olis[@]}" "$_odes" && return 0
     [ -n "$CEN_OPT_DRYRUN" ]                     # --dryrun always returns 0
 }
 
@@ -398,6 +406,94 @@ joinpath() {
 }
 
 # ------------------------------------------------------------------------------
+# matchpath - Match argument paths by type and access permission
+#
+# Call:    matchpath [-a <rslt>] [-c <func>] [-f|-d|-e] [-m] [-o] [-p] \
+#                    [-r|-w|-x]... [--] <path>...
+#
+#          Simple filtering of paths, no recursion. See also: [[walk()]].
+#
+# Options: -a  result array
+#          -c  call <func> for accepted item, ignore item on failure
+#          -d  match folders only
+#          -e  match existing paths only
+#          -f  match files only
+#          -m  match against --include/--exclude
+#          -o  return first match only
+#          -p  run prettypath on matches
+#          -r  path must be readable
+#          -w  path must be writable
+#          -x  path must be executable
+#
+# Return:   **true** if at least one file did match or **false** otherwise.
+#
+#.Examples: # get alternatives
+#.          matchpath -o ~/."$CEN_NAME" "/etc/default/$CEN_NAME"
+#.          message "Got:" "${CEN_MATCHPATH:--nothing-}"
+#
+#.          # get a list of files, report count
+#.          matchpath -a list -f -r -- *.c *.cpp *.h
+#.          pluralize -z -c 2 -- "${#list[@]}" 'file'
+#
+#.          # matching glob patterns
+#.          CEN_OPT_INCLEXCL=()                 # clear filter list
+#.          optarg - - -x '*.bak'               # exclude: *.bak
+#.          optarg - - -i '^centauri*'          # include: centauri*
+#.          matchpath -f -m -- *
+#
+#.          # use enumerator/filter callback
+#.          my_filter() {
+#.              [ -h "$1" ] || return 0         # accepted, good
+#.              message "Ignore symlink:" "$1" ; return 1
+#.          }
+#.          matchpath -a list -c my_filter -- * || quit "No match"
+# ------------------------------------------------------------------------------
+CEN_MATCHPATH=
+matchpath() {
+    local _oarr _oone _opre _otyp _orea _owri _oexe _scal=':' _smat=':'
+    while [ "${1::1}" = "-" ] ; do
+      case "$1" in
+      --)   shift ; break ;;
+      -a)   shift ; _oarr="$1" ;;
+      -c)   shift ; isfunction -f -- "$1" ; _scal="$1" ;;
+      -d)   _otyp='-d' ;;
+      -e)   _otyp='-e' ;;
+      -f)   _otyp='-f' ;;
+      -m)   _smat='filter' ;;
+      -o)   _oone=1 ;;
+      -p)   _opre=1 ;;
+      -r)   _orea=1 ;;
+      -w)   _owri=1 ;;
+      -x)   _oexe=1 ;;
+      *)    _cen_abort - "$1"
+      esac ; shift
+    done
+    local -n _varr="${_oarr:-CEN_MATCHPATH}" ; _varr=()
+    local _item _stat=1
+    for _item in "$@" ; do
+        $_smat -- "$_item" || continue
+        if [ -n "$_otyp" ] ; then
+            [ $_otyp "$_item" ] || continue
+        fi
+        if [ -n "$_orea" ] ; then
+            [ -r "$_item" ] || continue
+        fi
+        if [ -n "$_owri" ] ; then
+            [ -w "$_item" ] || continue
+        fi
+        if [ -n "$_oexe" ] ; then
+            [ -x "$_item" ] || continue
+        fi
+        _stat=0
+        [ -n "$_opre" ] && prettypath -s _item -p -- "$_item"
+        $_scal "$_item" || continue
+        _varr+=("$_item")
+        [ -n "$_oone" ] && break
+    done
+    return $_stat
+}
+
+# ------------------------------------------------------------------------------
 # move - Move (or rename) files or folders using /usr/bin/mv
 #
 # Call:    move [-f] [-o|-x] [-q|-s|-v] [-r] <src>... <dest>
@@ -459,7 +555,7 @@ move() {
 
     $_omsg -a -p $"Moving '%s' to '%s'" "${*:1:$#-1}" "$_dest"
 
-    sysrun $_orun $_osys -b -- mv -f -- "${@:1:$#-1}" "$_dest" && return 0
+    sysrun $_orun $_osys -b -w 'move()' -- mv -f -- "${@:1:$#-1}" "$_dest" && return 0
     [ -n "$CEN_OPT_DRYRUN" ]                     # --dryrun always returns 0
 }
 
@@ -538,6 +634,7 @@ prettypath() {
         esac ; shift
     done
     local -n _varg="$_fset" ; [ $# = 0 ] && set -- "$_varg"
+    _varg=
 
     if [ -n "$_oexi" ] ; then
         if [ ! -e "$1" ] ; then
@@ -727,6 +824,9 @@ remove() {
       esac ; shift
     done
 
+### TODO should not use unlink
+### TODO /usr/bin/rm should use --interactive=never (or </dev/null)
+
     # single argument - allow rmdir and unlink bash builtins
     if [ $# = 1 ] ; then
         [ "${1:--}" = "-" ] && return 0
@@ -834,15 +934,16 @@ rename() {
 # ------------------------------------------------------------------------------
 # resolve - Resolve and prettify (multiple) file/dir paths
 #
-# Call:     resolve [-a <arr>|-s <var>] [-t <trm>] [-e] [-f|-q] [-c|-m] [-p] <path>...
-#           resolve [-s <var>] [-e] [-f|-q] [-c|-m] [-p] -x|-y <exe>
+# Call:     resolve [-a <arr>|-s <var>] [-t <trm>] [-e] [-f|-q] [-c|-l|-m] [-p] <path>...
+#           resolve [-s <var>] [-e] [-f|-q] [-c|-l|-m] [-p] -x|-y <exe>
 #
-# Options:  -a  save result to array <arr>
+# Options:  -a  save result to array <arr> (default is CEN_RESOLVE)
 #           -c  canonicalize, ignore missing <path>s
 #           -e  error if <path>s does not exist
 #           -f  make errors fatal
+#           -l  read symlink(s) but do not canonicalize
 #           -m  canonicalize, including missing <path>s
-#           -s  save result to <var>
+#           -s  save result to <var> (default is CEN_RESOLVE)
 #           -t  trim prefix from result paths
 #           -f  make errors fatal
 #           -p  return pretty name, see [[prettypath()]]
@@ -880,6 +981,9 @@ rename() {
 #.          resolve -- here/* and/there*    # readlink execution would fail
 #.          resolve -e -- here/* and/there* # error message per missing item
 #
+#.          # read symlink (fails if arg is not a symlink)
+#.          resolve -q -l /usr/bin/sh && message "sh symlinked: $CEN_RESOLVE"
+#
 #.          # get my invokation path
 #.          resolve -x -p && message "Path:" "${CEN_RESOLVE%/*}"
 # ------------------------------------------------------------------------------
@@ -894,6 +998,7 @@ resolve() {
       -c)   _ocan='-e' ;;
       -e)   _xchk=1 ;;
       -f)   _xerr=fatal ; _osys="-f -p" ;;
+      -l)   _olnk='-l' ;;
       -m)   _ocan='-m' ;;
       -p)   _pret=1 ;;
       -q)   _xerr=: ; _osys="-q" ;;
@@ -941,12 +1046,12 @@ resolve() {
     fi
 
     # resolve symlinks
-    if [ -n "$_ocan" ] ; then
+    if [ -n "$_ocan" -o -n "$_olnk" ] ; then
         if [ $# = 1 ] ; then
             if [ "$_ocan" = '-e' ] && [ ! -e "$1" ] ; then
                 $_xerr $"No such file or folder:" "$1" ; return 1
             else
-                _cen_path_realp -c "$1" || return 1 ; set -- "$_logi"
+                _cen_path_realp ${_olnk:--c} "$1" || return 1 ; set -- "$_logi"
             fi
         elif [ $# -gt 1 ] ; then
             sysrun $_osys -a _vrrr -r -- readlink $_ocan -- "$@" || return 1
@@ -1314,9 +1419,9 @@ symlink() {
     # run 'ln' and disable builtin for option '-r'
     _etxt=$"Failed to create symbolic link"": $_link"
     if [ -n "$_orel" ] ; then
-        sysrun $_osys -m "$_etxt" -i -- ln $_onck -s -r -- "$_targ" "$_link" || return 1
+        sysrun $_osys -w 'symlink()' -m "$_etxt" -i -- ln $_onck -s -r -- "$_targ" "$_link" || return 1
     else
-        sysrun $_osys -b -m "$_etxt" -d -- ln $_onck -s "$_targ" "$_link" || return 1
+        sysrun $_osys -w 'symlink()' -b -m "$_etxt" -d -- ln $_onck -s "$_targ" "$_link" || return 1
     fi
     $_mesg -a -c $" created" -- "$_link => $_targ" ; return 0
 }
@@ -1451,7 +1556,7 @@ sysrun() {
         # option -n does no checks at all
         if [ -z "$_ffnd" ] ; then
             _opre=
-        # having a path disables -n and -p options
+        # having a path disables -n and -d options
         elif [ "${_xcmd/\//}" != "$_xcmd" ] ; then          # contains /
             _opre=
         # using sysfind and cache
@@ -1465,7 +1570,7 @@ sysrun() {
                 fi
             elif [ -n "$_xtmp" ] ; then                     # cached as command
                 _xtmp+="/$_xcmd"
-                if [ "$_ffnd" = '0' ] ; then                # force builtins ...
+                if [ "$_ffnd" = 0 ] ; then                  # force builtins ...
                     # check for builtin, clear search path to disable autoload
                     if BASH_LOADABLES_PATH= enable -a "$_xcmd" &>/dev/null ; then
                         _xtmp="$_xcmd"
@@ -1559,10 +1664,12 @@ sysrun() {
         $CEN_NOTRACE set -x ; return $_osta
     elif [ -n "$_ofmt" ] ; then                         # system -e -p style
         splitjoin -s _xtmp -d '\n' -i "$_vnam"
-        _xarg=
-        for _xtmp in "${_xtmp[@]}" ; do
-            _xarg+="${_xtmp#/*: *: }"$'\n'              # strip bash error prefix
-        done
+        _xarg="${_xtmp#/*: }"                           # strip file name prefix
+        if [ "$_xcmd" = 'builtin' -a "$_xarg" != "$_xtmp" ] ; then
+            _xarg="${_xarg#[[:alpha:]]*[0-9]: }"        # strip line number
+            _xarg="${_xarg#$1: }"                       # strip builtin name
+        fi
+        splitjoin -j _xarg -n -- "$_xarg" "${_xtmp[@]:1}"
         [ "$_xcmd" = 'builtin' ] && _xtmp=" $1" || _xtmp=
         $_ecmd -m -p "${_emsg} %s\n%s" "${_owho:-($_xcmd)}" "$_xtmp" "$_xmsg" "$_xarg"
     else                                                # simple ...
@@ -1585,6 +1692,7 @@ sysrun() {
 # Options:  -b  set base folder to <fldr> (default is $XDG_RUNTIME_DIR)
 #           -d  delete all files created by tmpfile for this process
 #           -f  make errors fatal
+#           -i  registers a subshell for its own base folder
 #           -n  do not actually create the file
 #           -p  create a pipe (fifo) instead of a file
 #           -r  ignore --dryrun
@@ -1646,6 +1754,7 @@ sysrun() {
 #.          wait ; quit                     # wait for subshell before quit
 # ------------------------------------------------------------------------------
 CEN_TMPFILE=
+CEN_EXT_TSUB=
 tmpfile() {
     local _odel _oftl _onoc _opip _oerr='error -z' _orun _updt _snam='CEN_TMPFILE' _base
     while [ "${1::1}" = "-" ] ; do
@@ -1655,6 +1764,7 @@ tmpfile() {
       -b)   shift ; [ "${1:--}" = '-' ] || _base="${1%/}" ; _updt=1 ;;
       -d)   _odel=1 ;;
       -f)   _oerr=fatal ; _oftl='-f' ;;
+      -i)   CEN_EXT_TSUB="$BASHPID" ; CEN_EXT_TPID= ; return 0 ;;
       -n)   _onoc=1 ;;
       -p)   _opip=1 ;;
       -r)   _orun='-r' ;;
@@ -1681,8 +1791,13 @@ tmpfile() {
 
     # temp file naming
     #       <name>-<$$>-<indx>              # main process
-    #       <name>-<$$>-<BASHPID>-<indx>    # child process
-    [ "$CEN_EXT_TPID" != "$$" ] && _ssuf="$BASHPID-"
+    #       <name>-<$$>-<BASHPID>-<indx>    # simple subshell
+    #       <name>-<BASHPID>-<indx>         # registered subshell, see -i
+
+    if [ "$CEN_EXT_TPID" != "$$" ] ; then               # we are a subshell ...
+        # use main base + suffix if not registered by -i option
+        [ "$CEN_EXT_TSUB" != "$BASHPID" ] && _ssuf="$BASHPID-"
+    fi
 
     # set base folder
 
@@ -1702,7 +1817,7 @@ tmpfile() {
             folder $_oftl $_orun -m -s _base -- "$_base" 700 || return 1
         fi
         CEN_EXT_TEMP=
-        _base+="/$CEN_NAME-$$-"
+        _base+="/$CEN_NAME-${CEN_EXT_TSUB:-$$}-"
     else
         _base="$CEN_EXT_TEMP"
     fi
diff --git a/library/_centauri_bash_lib b/library/_centauri_bash_lib
--- a/library/_centauri_bash_lib
+++ b/library/_centauri_bash_lib
@@ -36,7 +36,7 @@
 # coreutils bash builtins can be enabled. For more details see [[_centauri_bash_ext]]
 # and [[builtin]].
 #
-# Copyright Dr. J. Pfennig (c) 2007-2022
+# Copyright Dr. J. Pfennig (c) 2007-2023
 # ------------------------------------------------------------------------------
 
 declare -g -A CEN_MODULES['_centauri_bash_lib']='0.99:1:1'
@@ -311,15 +311,15 @@ error() {
     [ -n "$_fopt" ] && fatal ${_popt[@]} -- "$@"
     [ -n "$CEN_NOTRACE" ] && [ -z "$_isok" -a -n "$*" ] && message -e ${_popt[@]} -- "$@"
     [ "$CEN_DONE" = 1 ] && CEN_DONE=2
-    [ "$CEN_EXIT" -le 1 ] && CEN_EXIT=2
-    return "${_zero:-$CEN_EXIT}"
+    [ "${CEN_EXIT:-0}" -le 1 ] && CEN_EXIT=2
+    return ${_zero:-$CEN_EXIT}
 }
 
 # ------------------------------------------------------------------------------
 # fatal - fatal error message, terminate via quit()
 #
 # Call:     fatal [-a|-i] [-m|-n] [-p] [-r] [--] <msg>...
-#           fatal -t <msg>...                               # call trace
+#           fatal -t [-p <fmt>] <msg>...                    # call trace
 #
 # Options:  ... most [[message()]] options (using **message -f**)
 #
@@ -360,7 +360,7 @@ fatal() {
 #           quit -h
 #
 # Options:  ... most [[message()]] options (the implementation calls **message**)
-#           -e  check for error, print "Terminated after error" if 1st arg is not '-'
+#           -e  error exit, print "Terminated after error" if 1st arg is not '-'
 #           -h  just run ''quit'' hook and reset to default (save for subshell)
 #           -s  override the exit code (CEN_EXIT)
 #           -t  sets CEN_EXIT=4, print "Terminated" if 1st arg is not '-'
@@ -380,8 +380,12 @@ fatal() {
 #.              $DAT_QUIT_LIST "$@"         # IMPORTANT: pass all args!
 #.          }
 #.
+#.          # explicitly register the hook function ...
 #.          DAT_QUIT_LIST="$CEN_HOOK_QUIT"  # save top of list
 #.          CEN_HOOK_QUIT=my_quit ; quit    # register hook and call
+#.
+#.          # ... or register the hook function via context -h
+#.          context -h CEN_HOOK_QUIT DAT_QUIT_LIST my_quit
 #
 #+Internally quit gets called by some traps. See: [[context()]], [[fatal()]],
 # [[main()]] and [[error()]]. But it never uses EXIT, RETURN or DEBUG traps.
@@ -419,7 +423,7 @@ quit() {
       --)   shift ; break ;;
       -e)   _flgt=2 ; _opts+=("$1") ; [ "$CEN_EXIT" = 0 ] && CEN_EXIT=1 ;;
       -h)   $CEN_HOOK_QUIT -h ; CEN_HOOK_QUIT=_cen_quit ; return 0 ;;
-      -s)   CEN_EXIT="$2" ; shift ;;
+      -s)   CEN_EXIT="${2:-0}" ; shift ;;
       -t)   _flgt=1 ; CEN_EXIT=4 ;;
       -y)   CEN_QUIT_SANE=1 ;;
       -)    break ;;                        # special case
@@ -457,7 +461,10 @@ _cen_quit() {
     done || :
     $CEN_NOTRACE set -x
 
-    [ -n "$CEN_QUIT_WSUB" ] && wait                     # wait for subshells
+    if [ -n "$CEN_QUIT_WSUB" ] ; then                   # wait for subshells
+        $CEN_TRACE -a -c - $"Waiting for children"
+        wait
+    fi
     CEN_HOOK_QUIT=_cen_exit
     if [ $# = 1 -a "$1" = '-h' ] ; then
         _cen_exit -
@@ -473,7 +480,7 @@ _cen_exit() {
     isfunction -c '_cen_pro_quit' || :          # remove progress output
     isfunction -c '_cen_ext_quit' || :          # run quit tmpfile late
     [ "$1" = '-' ] && return 0                  # see quit -h
-    $CEN_TRACE -r -c $"Exit status" -- "${CEN_EXIT:-0}"
+    $CEN_TRACE2 -r -c $"Exit status" -- "${CEN_EXIT:-0}"
     [ -n "$CEN_QUIT_SANE" ] && system -r -q -- stty sane
     if [ "$CEN_QUIT_WAIT" = 3 ] ; then
         system -b -r sleep 2
@@ -571,7 +578,7 @@ _cen_message() {
     if [ -n "$CEN_CONS_MSGLEN" ] ; then         # see progress(), ignore -q
         echo 1>&2 ; CEN_CONS_MSGLEN=            #     needed for trace()
     fi
-    [ "$_verb" -gt 0 ] || return "$_stat"       # global -q option
+    [ "$_verb" -gt 0 ] || return $_stat         # global -q option
 
     [ "$CEN_AUTOIND" = 2 ] && _sind=1 ; CEN_AUTOIND=1
     [ -n "$_sind" ] && _snam="${_snam//?/ }"    # no program name
@@ -596,7 +603,7 @@ _cen_message() {
             shift ; _snam="${_snam//?/ }" ; _serr=
         done
     fi 1>&2
-    return "$_stat"                             # error/fatal return CEN_EXIT
+    return $_stat                               # error/fatal return CEN_EXIT
 }
 
 # format short message: <vnam> <orig>|- <mesg>
@@ -871,7 +878,7 @@ confirm() {
         if [ -n "$CEN_YESNO" ] ; then
             _varg="$CEN_YESNO"
             [ "$CEN_YESNO" = "y" ] || return 1
-            $CEN_TRACE -a "confirm:" "$@" ; return 0
+            $CEN_TRACE -a -c " yes" "$@" ; return 0
         fi
         [ -z "$_dflt" ] && _dflt=$"no"
         [ -z "$_vali" ] && _vali=$"yes no"
@@ -972,7 +979,7 @@ _cen_getline() {
 #
 # Call:     (1) context -e <mask> ...
 #           (2) context -g <mode> ...
-#           (2) context -h <hnam> <vnam> <hook> ...
+#           (3) context -h <hnam> <vnam> <hook> ...
 #           (4) context -t [<trap>|+|-] ...
 #           (5) context -v [0-3] ...
 #           (6) context ... [-r] [-s] [-c|-q|-x] [--] <arg>...
@@ -1014,7 +1021,7 @@ _cen_getline() {
 # 'command not found' function (bit 2). **DO NOT** run "set -eE" directly.
 #
 #+Form (2): The -g option will load the [[_centauri_bash_con]] or [[_centauri_bash_win]]
-# module, depending on <mode>.
+# module, depending on <mode>. See [[quit()]] option -h for an example.
 #
 #+Form (3): Adds a hook function to a hook chain if variable <vnam> is empty.
 #
@@ -1220,7 +1227,6 @@ context() {
     if [ -n "$CEN_DISPLAY" ] && [ "${CEN_IS_DESKTOP:-0}" != 0 -o "$_cons" = 2 ] ; then
         if embed -r -q '_centauri_bash_run' ; then
             if [ "$_cons" = 2 ] ; then                  # force a console window ...
-#                terminal -f -o 1 -m 3 -t "$_text" -r -- $_sudo "$@" && return 2 || return 1
                 terminal -f -o 1 -t "$_text" -r -- $_sudo "$@"
             else                                        # exec console, no return on success
                 terminal -f -m 1 -t "$_text" -r -- $_sudo "$@"
@@ -1329,8 +1335,6 @@ create() {
             :
         elif [ "$#" = 1 ] && [ -f "$_fout" -a -w "$_fout" ] ; then
             >"$_fout" || _stat=$?                   # really truncate
-        elif [ -n "$CEN_FEATURE_A" ] ; then         # can use builtins...
-            remove $_frun -s -- "$_fout"
         elif [ -e "$1" ] ; then
             system $_frun -b -e -p -- rm -f -- "$_fout"
         fi
@@ -1610,19 +1614,19 @@ filter() {
       *)   _cen_abort - "$1"
       esac ; shift
     done
-    [ "${#CEN_OPT_INCLEXCL[@]}" = 0 ] && return "${_rval:-0}"
+    [ "${#CEN_OPT_INCLEXCL[@]}" = 0 ] && return ${_rval:-0}
     _vall="$1" ; [ -n "$_oinv" ] && _vall="${1,,}"
 
     for _valu in "${CEN_OPT_INCLEXCL[@]}" ; do
         if [ -n "$_valu" ] ; then
             [ "$_excl" = 0 ] && _iinc=1
             [ -n "$_oinv" ] && _valu="${_valu,,}"
-            [[ "$_vall" == $_valu ]] && return "$_excl"
+            [[ "$_vall" == $_valu ]] && return $_excl
         fi
         [ "$_excl" = 0 ] && _excl=1 || _excl=0
     done
 
-    [ -n "$_rval" ] && return "$_rval"
+    [ -n "$_rval" ] && return $_rval
     [ "$_iinc" = 0 ]            # fail if we had includes
 }
 
@@ -1764,7 +1768,7 @@ folder() {
     [ "$_vval" = '/' ] || _vval="${_vval%/}"
     [ -z "$_ogen" ] && while [ ! -d "$_vval" ] ; do
         if [ -n "$_omak" ] ; then
-            create -d $_oopt $_rdry -- "$_vval" $2 $3 && break
+            create -d $_oopt $_rdry -- "$_vval" "$2" "$3" && break
         elif [ -n "$_tdir" -a "$_ocwd" = ":" ] ; then
             return 1                            # do not clear _vval!
         else
@@ -1898,11 +1902,11 @@ invoke() {
     if ! isfunction "$nact" ; then
         error -z $"Not yet implemented:" "$CEN_ACTION"
     elif [ -n "$CEN_OPT_TRACE" ] ; then
-        $CEN_TRACE -r -c " '$CEN_ACTION'" "$nact"
+        $CEN_TRACE2 -r -c " '$CEN_ACTION'" "$nact"
         # must catch ERR trap in _cen_abort
         CEN_NOTRACE= ; set -x ; $nact "${CEN_ACTARR[@]}" ; set +x ; CEN_NOTRACE=:
     else
-        $CEN_TRACE -r -c " '$CEN_ACTION'" "$nact"
+        $CEN_TRACE2 -r -c " '$CEN_ACTION'" "$nact"
         # must catch ERR trap in _cen_abort
         $nact "${CEN_ACTARR[@]}"
     fi
@@ -2060,6 +2064,7 @@ optarg() {
     -i|-x)
        local _temp="$CEN_ACTARR" ; _vnam=
        case "$_temp" in
+       *\**)    ;;
        ^*\$)    _temp="${_temp:1}" ; _temp="${_temp%\$}" ;;
        ^*)      _temp="${_temp:1}*" ;;
        *\$)     _temp="*${_temp%\$}" ;;
@@ -2484,7 +2489,8 @@ _cen_sudo() {
 
 system() {
     $CEN_NOTRACE set +x
-    local _ferr _good=0 _mind _nout _val_ _vset _vdel _xcmd _stat=0 _sudo _cpro _rdry _bflg _zflg _temp
+    local _ferr _mind _nout _val_ _vset _vdel _xcmd _sudo _cpro _rdry _bflg _xflg _zflg _temp
+    local _good=0 _stat=0
     while [ "${1::1}" = '-' ] ; do
       case "$1" in
       --)   shift ; break ;;
@@ -2510,42 +2516,44 @@ system() {
             [ "$CEN_VERB" -gt 1 ] && _nout=3
             [ "$CEN_VERB" -lt 1 ] && _nout=1 ;;
       -w)   _ferr="-w" ;;
-      -x)   _xcmd="exec" ;;
+      -x)   _xflg=1 ;;
       -z)   _zflg=1 ;;
       *)    _cen_abort - "$1"
       esac ; shift
     done
 
-    if [ "$1" = "eval" ] ; then
-        [ -n "$_sudo" ] && { shift ; _sudo+=("${CEN_PATHS[1]}/bash" -c); }
-    elif [ "$_cpro" = 1 ] ; then                        # option -c
+    if [ "$_cpro" = 1 ] ; then                          # option -c
         sysfind -c $_bflg $_ferr -- "$@" || _stat=127
-        $CEN_NOTRACE set -x ; return "$_stat"
+        $CEN_NOTRACE set -x ; return $_stat
+    elif [ "$1" = 'eval' ] ; then
+        [ -n "$_sudo" ] && _xcmd=("${CEN_PATHS[1]}/bash" -c "${*:1}")
     elif [ -z "$_cpro" ] ; then                         # no -n option
-        _temp="${CEN_COMMANDS["${1:-/}"]}"
-        if [ -z "$_temp" ] ; then                       # not cached, try to add it
+        _temp="${CEN_COMMANDS["${1:-/}"]}"              # cached command?
+        case "$_temp" in
+        '')     ;;                                      # not cached
+        -)      [ -z "$_bflg" ] && _temp= ;;            # is builtin, want cmd
+        *)      [ -n "$_bflg" ] && _temp= ;;            # is cmd, want builtin
+        esac
+
+        if [ -z "$_temp" ] ; then                       # get builtin or path
             [ "$_nout" = 1 ] && _temp= || _temp="${_ferr:--e}"
-            if ! sysfind -c $_bflg $_temp -- "$1" ; then
+            [ -n "$_xflg" ] && _bflg=
+            if ! sysfind -c -d $_bflg $_temp -- "$1" ; then
                 $CEN_NOTRACE set -x ; return 127
             fi
-            _temp="${CEN_COMMANDS["$1"]}"
+            _temp="${CEN_COMMANDS["${1:-/}"]}"          # cached command?
         fi
-        if [ "$_temp" = '-' ] ; then                    # cached as builtin
-            if [ -z "$_bflg" ] ; then                   # run external...
-                [ "$_nout" = 1 ] && _temp= || _temp="${_ferr:--e}"
-                if ! sysfind -c -i -s _temp $_temp -- "$1" ; then
-                    $CEN_NOTRACE set -x ; return 127
-                fi
-            elif [ -z "$_xcmd" ] ; then
-                _xcmd="builtin"
-            fi
-        elif [ -n "$_temp" ] ; then                     # cached as command
-            _temp+="/$1"
-            shift ; set -- "${_temp/\/\//\/}" "$@"
+        if [ "$_temp" = '-' ] ; then                    # got builtin
+            _xcmd=(builtin "$@")                        # assemble command
+        else
+            _temp+="/$1" ; _temp="${_temp/\/\//\/}"
+            _xcmd=("$_temp" "${@:2}")                   # assemble command
         fi
     fi
 
-    _xcmd=($_xcmd "${_sudo[@]}" "$@")                   # assemble command
+    [ -z "$_xcmd" ] && _xcmd=("$@")
+    [ -n "$_sudo" ] && _xcmd=("${_sudo[@]}" "${_xcmd[@]}")
+    [ -n "$_xflg" ] && _xcmd=(exec "${_xcmd[@]}")
     if dryrun $_rdry -- "${_xcmd[@]}"; then
         $CEN_NOTRACE set -x ; return 1
     fi
@@ -2578,7 +2586,7 @@ system() {
     fi
 
     if [ "$_stat" -le "$_good" ] ; then
-        $CEN_NOTRACE set -x ; return "$_stat"
+        $CEN_NOTRACE set -x ; return $_stat
     elif [ "$_nout" = 2 -a -n "$_val_" ] ; then
         if [ -z "$_ferr" ] ; then
             message $_mind -m -- "$_val_"
@@ -2591,7 +2599,7 @@ system() {
         message $_ferr -p -- $"Running '%s' failed with status %s" "$1" "$_stat"
     fi
     [ -n "$_ferr" ] && CEN_AUTOIND=
-    $CEN_NOTRACE set -x ; return "$_stat"
+    $CEN_NOTRACE set -x ; return $_stat
 }
 
 # ------------------------------------------------------------------------------
@@ -2699,7 +2707,7 @@ main() {
             _oinf=1 ; CEN_FEATURE_D=1 ; CEN_FEATURE_Y=1 ;;
         --pager)
             if embed -r -q '_centauri_bash_pip' ; then
-                optarg 'pager' - -t ; syspager -y
+                optarg 'pager' - -t ; syspager -y -d -c ''
             else
                 _isok=
             fi
diff --git a/library/_centauri_bash_svc b/library/_centauri_bash_svc
--- a/library/_centauri_bash_svc
+++ b/library/_centauri_bash_svc
@@ -129,7 +129,8 @@ CEN_SVC_RUNNING=                # used by _cen_svc_action (internal)
 CEN_SVC_AUTO_INIT=              # init early as service, see -n on load
 CEN_SVC_INHIBIT=                # see inhibit
 CEN_SVC_LOGPID=                 # used for logger
-CEN_SVC_SYSLOG=                 # actual logging mode
+
+export CEN_SVC_SYSLOG=          # actual logging mode (environment import)
 
 CEN_SVC_SYSD="$CEN_ROOT/systemd"        # systemd service folder (only if installed)
 CEN_SVC_SYSV="${CEN_PATHS[2]}/init.d"   # SysV service folder
@@ -158,31 +159,41 @@ isfunction -y progress
 # ------------------------------------------------------------------------------
 # background - Run a script in background, redirect input/output
 #
-# Call:      background [-m <suff>] [-n] [-o <file>|-s] [-w] <script> <arg>...
+# Call:     (1) background [-m <suff>] [-n] [-o <file>|-s] [-w] <script> <arg>...
+#           (2) background -c <pid>|<file> /|<pown>...
 #
-# Options:  -m  move non-empty output-file (overrides previous backup)
+#+          Form (1) starts a background subshell, see examples. Form (2) sets the
+#           **cgroup** of process-id <pid> (<pid> can be the path of a pidfile).
+#
+# Options:  -c  move <pid> into cgroup "_centauri-bash-lib" or <pown>
+#           -m  move non-empty output-file (overrides previous backup)
 #           -n  don't background, just redirect input/output
 #           -i  input from file (redirects **stdin**)
 #           -o  output to file (redirects **stdout** and **stderr**)
 #           -s  output to **syslog** (via [[message()]] et al)
 #           -w  no disown, simple subshell, set CEN_QUIT_WSUB for [[quit()]]
 #
-# variable: CEN_BACKGROUND  PID of the ''background'' process
+#+Cgroups:  <pown>... is a list of potential destination cgroups, the 1st existing
+#           will be used. Specifying "/" uses "centauti-bash-lib" which will be
+#           created if needed.
 #
-#+Warning:  If this function is used by a systemd service, it will not prevent systemd
-#           from terminating the background thread when the service **cgroup** is closed.
+# Variable: CEN_BACKGROUND  process-id of the ''background'' process
 #
-#.Example:  run_bgnd() {                            # list environment
+#+Warning:  If (1) is used by a systemd service, it will not prevent systemd from
+#           terminating the background thread when the service **cgroup** is closed.
+#           Consider using (2) to move the process to another **cgroup**.
+#
+#.Examples: run_bgnd() {                            # list environment
 #.              local larr=()
 #.              system -a larr -- env
 #.              splitjoin -x message -i larr
 #.          }
 #.
-#.          embed -m "_centauri_bash_svc"           # if needed
-#.
 #.          background run_bgnd                     # no output
-#.          background -s run_bgnd                  # to syslog
-#.          background -o "$CEN_NAME.log" run_bgnd  # to file
+#.          background -c "$CEN_BACKGROUND" "/"     # optional: change cgroup
+#.
+#.          background -s run_bgnd                  # output to syslog
+#.          background -o "$CEN_NAME.log" run_bgnd  # ... to file
 #.          background -n -o x.log -m old run_bgng  # logfile only
 #.          background -w -o - run_bgnd             # keep output, no disown
 #
@@ -203,12 +214,13 @@ isfunction -y progress
 # ------------------------------------------------------------------------------
 CEN_BACKGROUND=
 background() {
-    local _fmov _fnot _finp _fout _fwai _slog="$CEN_SVC_SYSLOG" _mesg="<none>"
+    local _cgrp _fmov _fnot _finp _fout _fwai _slog="$CEN_SVC_SYSLOG" _mesg="<none>"
     CEN_BACKGROUND=
 
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
+      -c)   shift ; _cgrp="$1" ;;
       -i)   shift ; _finp="$1" ;;
       -m)   shift ; _fmov="$1" ;;
       -n)   _fnot=1 ;;
@@ -219,6 +231,38 @@ background() {
       esac ; shift
     done
 
+    # change cgroup of a process
+    if [ -n "$_cgrp" ] ; then
+        if [ ! -e '/proc/self/cgroup' ] ; then
+            message -a -c " cgrp" "Not supported" ; return 1
+        fi
+        local _curr _cpro
+        if [ -n "${_cgrp//[0-9]/}" ] ; then             # got a pid file
+            if ! read _cgrp 2>/dev/null <"$_cgrp" ; then
+                error "background: Cannot read:" "$_cgrp" ; return 1
+            fi
+        fi
+
+        for _curr in "$@" ; do
+            if [ "$_curr" = '/' ] ; then
+                _curr="/sys/fs/cgroup/centauri-bash-lib"
+                folder -m "$_curr" || return 1
+                _cpro="$_curr/cgroup.procs"
+            else
+                _cpro="/sys/fs/cgroup/system.slice/$_curr/cgroup.procs"
+                [ -e "$_cpro" ] || continue
+            fi
+            if echo 2>/dev/null "$_cgrp" >"$_cpro" ; then
+                $CEN_TRACE -a -c " cgrp" -p "Moved 'pid=%s' to '%s'" "$_cgrp" "$_curr"
+                return 0
+            fi
+            error -p "background: Failed to move 'pid=%s' to '%s'" "$_cgrp" "$_curr"
+            return 1
+        done
+        error "background: New cgroup not found" ; return 1
+    fi
+
+    # run in background
     if [ -n "$_fmov" ] && [ -s "$_fout" ] ; then
         [ "${_fmov/./}" = "$_fmov" ] && _fmov="$_fout.$_fmov"
         $CEN_TRACE -a $"Renaming old output:" "$_fout  => $_fmov"
@@ -232,17 +276,19 @@ background() {
         JOURNAL_STREAM= $@ <"${_finp:-/dev/null}" &>>"${_fout:-/dev/null}"
     elif [ "$_fout" = '-' ] ; then
         $CEN_TRACE -a $"Run in background:" "$*"
-        {   CEN_EXIT= ; $@
+        {   [ -z "$_fwai" ] && tmpfile -i               # own base folder
+            CEN_EXIT=0 ; $@
             [ "$CEN_EXT_TPID" = "$BASHPID" ] && tmpfile -d
-            exit "${CEN_EXIT:-0}"
+            exit ${CEN_EXIT:-0}
         } <"${_finp:-/dev/null}" &
         CEN_BACKGROUND=$!
         [ -n "$_fwai" ] && CEN_QUIT_WSUB=1 || disown -h $!
     else
         $CEN_TRACE -a -p $"Run in background (output '%s'): %s" "${_fout:-$_mesg}" "$*"
-        {   CEN_EXIT= ; JOURNAL_STREAM= $@
+        {   [ -z "$_fwai" ] && tmpfile -i               # own base folder
+            CEN_EXIT=0 ; JOURNAL_STREAM= $@
             [ "$CEN_EXT_TPID" = "$BASHPID" ] && tmpfile -d
-            exit "${CEN_EXIT:-0}" ;
+            exit ${CEN_EXIT:-0}
         } <"${_finp:-/dev/null}" &>>"${_fout:-/dev/null}" &
         CEN_BACKGROUND=$!
         [ -n "$_fwai" ] && CEN_QUIT_WSUB=1 || disown -h $!
@@ -342,7 +388,7 @@ pidfile() {
 
     local _name="${1:-$CEN_NAME}" _file="$CEN_ROOT/transient" _temp
     [ -w "$_file" ] || _file="/run"
-    [ -w "$_file" ] || _file="$TMP"
+    [ -w "$_file" ] || _file="${TMPDIR:-$TMP}"
     _file+="/${_name##*/}$_fext"
 
     if [ -n "$_flgw" ] ; then                           # write pid file...
@@ -595,8 +641,7 @@ isservice() {
 # ------------------------------------------------------------------------------
 # runservice - start/stop/test services
 #
-# Call:     runservice [-d] [-r] [-u] [-e|-f] [-v] <verb> <name>...
-#           runservice [-d] [-r] [-u] [-e|-f] [-v] <name> <verb>    # deprecated
+# Call:     runservice [-d] [-r] [-u] [-e|-f] [-v] [-n] <verb> <name>...
 #
 #           runservice [-d] [-u] [-e|-f] [-v] <name>                # deprecated
 #           runservice [-d] [-u] [-e|-f] [-v] **test** <name>...
@@ -606,6 +651,7 @@ isservice() {
 # Options:  -d  run as a daemon, needs no root priviledge or service install
 #           -e  report errors
 #           -f  make errors fatal
+#           -n  non-blocking operation (systemd only)
 #           -r  ignore dryrun
 #           -s  silent mode, don't report invalid services or no find
 #           -u  use systemd user instance (error if not running systemd)
@@ -652,91 +698,95 @@ isservice() {
 #.          runservice stop inetd nmbd  # stop inetd and nmbd
 #.          runservice -d start dscipt  # start 'dscript' as daemon
 # ------------------------------------------------------------------------------
-export CEN_RUNSERVICE
+CEN_RUNSERVICE=
 runservice() {
-
     CEN_RUNSERVICE=
-    local _daem _rdry _slnt _user _suff _verb="trace" _inst="system" _oerr="trace"
+    local _daem _rdry _user _suff _verb='trace' _inst='system' _oerr='trace' _oslt _onob
     local _sdir=("${CEN_PATHS[2]}/systemd" "$CEN_PATHS/run/systemd"
                  "$CEN_PATHS/lib/systemd" "$CEN_PATHS/usr/lib/systemd")
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -d)   _daem=1 ;;
-      -e)   _oerr="error" ;;
-      -f)   _oerr="fatal" ;;
-      -r)   _rdry="-r" ;;
-      -s)   _slnt=1 ;;
+      -e)   _oerr='error' ;;
+      -f)   _oerr='fatal' ;;
+      -n)   _onob='--no-block' ;;
+      -r)   _rdry='-r' ;;
+      -s)   _oslt='trace' ;;
       -u)   if [ -z "$CEN_SVC_SYSD" ] ; then
                 error $"Service command depends on 'systemd'" ; return 1
             fi
             _sdir+=(~/.config/systemd ~/.local/share/systemd)
-            _inst="user" ; _user="--user" ;;
-      -v)   _verb="message" ;;
+            _inst='user' ; _user='--user' ;;
+      -v)   _verb='message' ;;
       *)    _cen_abort - "$1"
       esac ; shift
     done
+    [ -z "$_oslt" ] && _oslt="$_oerr"
 
     [ "$_verb" = "message" -a "$_oerr" = "trace" ] && _oerr="message"
     [ "$_oerr" != "trace" ] && _verb="message"
     local _stmp _scmd="$1" ; shift
 
-    # single argument: assume "test"
-    if [ $# = 0 ] ; then
+    # check verb
+    case "$_scmd" in
+    start|stop|restart|status|test)
+        ;;
+    *)
+        [ $# = 0 ] || _cen_abort - "$_scmd"
+        # single argument: assume "test"
         set -- "$_scmd" ; _scmd="test"
-
-    # backward compatibility - swap arguments
-    elif [ $# = 1 ] ; then
-        case "$1" in
-        start|stop|restart|status)
-            _stmp="$1"
-            set -- "$_scmd" ; _scmd="$_stmp" ;;
-        esac
-    fi
+    esac
 
     # test if services exist and are not masked
 
     local _curr _serr=0 _sarg _slst=()
     [ $# -gt 1 ] && _sarg="$*"
     while [ $# -gt 0 ] ; do
+        local _name="$1" _base="${1%%@*}"
+        [ "$_name" = "$_base" ] || _base+='@'
         # run as a daemon?
         if [ -n "$_daem" ] ; then
-            if [ -x "$1" ] ; then
-                _slst+=("$1")
+            if [ -x "$_name" ] ; then
+                _slst+=("$_name")
             else
-                $_oerr -a $"Not a daemon:" "$1"
+                $_oerr -a $"Not a daemon" "($_scmd): $_name"
                 _serr=1
             fi
 
         # do we have a valid service?
         else
             # is it an unmasked service?
-            [ -n "$CEN_SVC_SYSD" ] && for _curr in "${_sdir[@]}" "" ; do
-                [ -d "$_curr" ] || continue
-                _curr+="/$_inst"
-                if   [ -e "$_curr/$1.service" ] ; then
-                    _suff=".service"
-                elif [ -e "$_curr/$1.target" ] ; then
-                    _suff=".target"
-                else
-                    continue
-                fi
-                if [ "$_curr/$1$_suff" -ef "/dev/null" ] ; then
-                    [ -z "$_slnt" ] && $_oerr $"Service is masked:" "$1"
-                    ((_serr |= 2)) ; break
-                else
-                    _slst+=("$1$_suff") ; break
-                fi
-            done
+            if [ -n "$CEN_SVC_SYSD" ] ; then
+                for _curr in "${_sdir[@]}" "" ; do
+                    [ -d "$_curr" ] || continue
+                    _curr+="/$_inst"
+                    if   [ -e "$_curr/$_base.service" ] ; then
+                        _suff=".service"
+                    elif [ -e "$_curr/$_base.target" ] ; then
+                        _suff=".target"
+                    else
+                        continue
+                    fi
+                    if [ "$_curr/$_base$_suff" -ef "/dev/null" ] ; then
+                        $_oslt $"Service is masked" "($_scmd): $_base"
+                        ((_serr |= 2)) ; break
+                    else
+                        _slst+=("$_name$_suff") ; break
+                    fi
+                done
+            fi
 
             if [ -z "$_curr" -o -z "$CEN_SVC_SYSD" ] ; then
                 # check for sysv
-                if [ -x "$CEN_SVC_SYSV/$1" ] ; then
-                    _curr="$CEN_SVC_SYSV/$1"
-                    _slst+=("$1")
+                if [ -x "$CEN_SVC_SYSV/$_name" ] ; then
+                    _curr="$CEN_SVC_SYSV/$_name"
+                    _slst+=("$_name")
                 else
-                    [ -z "$_sarg" ] &&
-                        $_oerr $"Not a service:" "$1" || $_verb -a $"Not a service:" "$1"
+                    [ -z "$_sarg" -a "$_oerr" != 'trace' ] &&
+                        $_oerr $"Not a service" "($_scmd): $_name"
+                    [ -z "$_sarg" -a "$_oerr"  = 'trace' ] &&
+                        $_verb -a $"Not a service" "($_scmd): $_name"
                     ((_serr |= 1))
                 fi
             fi
@@ -744,10 +794,10 @@ runservice() {
         shift
     done
     if [ -z "$_slst" ] ; then
-        [ -n "$_sarg" -a -z "$_slnt" ] && $_oerr -a $"No valid service found:" "$_sarg"
+        [ -n "$_sarg" ] && $_oslt -a $"No valid service found" "($_scmd): $_sarg"
         ((_serr |= 64)) ; return $_serr
     elif [ "$_serr" != 0 ] ; then
-        [ -z "$_slnt" ] && $_oerr $"Invalid service(s) found"
+        $_oslt $"Invalid service(s) found" "($_scmd)"
     fi
 
     # translate operation text
@@ -783,7 +833,7 @@ runservice() {
             embed -- "$_stmp" $_scmd --daemon=1 || _stat=$? ; _kind=$"Daemon"
         done
     elif [ -n "$CEN_SVC_SYSD" ] ; then
-        sysrun $_rdry -n -p -- systemctl $_user "$_scmd" "${_slst[@]}"
+        sysrun $_rdry -n -p -- systemctl $_onob $_user "$_scmd" "${_slst[@]}"
         _stat=$? ; _kind=$"Service (systemd)"
     else
         for _stmp in "${_slst[@]}" ; do
@@ -937,7 +987,7 @@ _cen_svc_action() {
                     shift ; CEN_ACTARR=("$scmd" "$@")
                     set -- "$CEN_ACTION" "$scmd" "$@"
                     _cen_svc_user "$@" && return        # fwd to user code
-                    embed -m "_centauri_bash_ins" ; _cen_svc_trace _cen_ins_service "$scmd"
+                    embed -m '_centauri_bash_ins' ; _cen_svc_trace _cen_ins_service "$scmd"
                     CEN_ARGS=0 ; return
                     ;;
 
@@ -1005,17 +1055,24 @@ _cen_svc_action() {
         _cen_svc_state "start" || return                # check/update state
         _cen_svc_forking                                # fork simple service
         if ! _cen_svc_user "$@" ; then                  # fwd to user code
-            if [ "$CEN_SVC_TYPE" != "oneshot" ] ; then  # catch signal, call run()
-                CEN_SVC_RUNNING="running"
+            if [ "$CEN_SVC_TYPE" != 'oneshot' ] ; then  # catch signal, call run()
+                CEN_SVC_RUNNING='running'
                 context -t _cen_svc_sigterm             # set trap handler
                 isfunction -c run                       # call run() if existing
             fi
         fi
-        _cen_svc_state "drop"                           # opt. delete pid file
     fi
 
     _cen_svc_fancy end ; CEN_SVC_RUNNING=               # service now inactive
     CEN_ARGS=0                                          # ignore missing action()
+}
+
+# ------------------------------------------------------------------------------
+# hook quit
+# ------------------------------------------------------------------------------
+_cen_svc_quithook() {
+    [ -n "$CEN_SVC_TYPE" ] && _cen_svc_state 'quit'     # opt. delete pid file
+    $CEN_SVC_HOOK_QUIT "$@" ; return                    # chaining
 }
 
 # ------------------------------------------------------------------------------
@@ -1034,7 +1091,7 @@ _cen_svc_sigterm() {
 }
 
 # ------------------------------------------------------------------------------
-# PID file state manager: start|stop|drop|kill
+# PID file state manager: start|stop|quit|error|kill
 # ------------------------------------------------------------------------------
 _cen_svc_state() {
     local _fpid _frun
@@ -1042,10 +1099,10 @@ _cen_svc_state() {
     # error handler (called by recusion)
     if [ "$1" = "error" ] ; then
         [ -n "$CEN_OPT_FORCE" -o -n "$CEN_OPT_ZOMBIE" ] && return
-        error -s 4
+        error -s 4 ; CEN_SVC_TYPE=
         [ -n "$CEN_FEATURE_F" ] && _frun="--force" || _frun="--zombie"
         if [ "$2" = "start" ] ; then
-            [ "$3" = "1" ] && _fpid="service" || _fpid="daemon"
+            [ "$3" = 1 ] && _fpid=$"service" || _fpid=$"daemon"
             quit -p -m $"Not starting, already running as a %s\nUse '%s' to override or delete '%s'" \
                 "$_fpid" "$_frun" "$CEN_PIDFILE"
         else
@@ -1072,6 +1129,7 @@ _cen_svc_state() {
         fi
         ;;
     *)
+        [ "$1" = 'quit' ] && return
         _cen_abort - "$CEN_SVC_TYPE"
     esac
 
@@ -1080,10 +1138,9 @@ _cen_svc_state() {
         dryrun -s "$1, terminating" && exit 0       # HACK stop on dryrun
     [ "$CEN_OPT_DAEMON" = "0" ] || _frun="-r"
 
-    # remove pid file if type is 'once|daemon' or after error
-    if [ "$1" = "drop" ] ; then
-        [ "$CEN_SVC_TYPE" != "once" -a "$CEN_SVC_TYPE" != "daemon" ] &&
-            error -t && return
+    # remove pid file if type is 'once' or after error
+    if [ "$1" = 'quit' ] ; then
+        [ "$CEN_SVC_TYPE" != 'once' ] && error -t && return
         pidfile $_frun -d -- "$CEN_NAME" ; return
     fi
 
@@ -1104,11 +1161,11 @@ _cen_svc_state() {
         else
             pidfile $_frun -d -- "$CEN_NAME"        # remove pid file olny
         fi
+        CEN_SVC_TYPE=
 
     elif [ "$1" = "status" ] ; then                 # --- status only
         [ "$_fact" = "1" ] && CEN_SVC_RUNNING="1: "$"running as service"
         [ "$_fact" = "2" ] && CEN_SVC_RUNNING="2: "$"running as daemon"
-        return
 
     else                                            # --- check stop conflict
         if [ -z "$_fact" ] ; then                   # no pid file
@@ -1121,6 +1178,7 @@ _cen_svc_state() {
                 $"Daemon '%s' is running as service, cannot stop" "$CEN_NAME"
         fi
         pidfile $_frun -d -k - -- "$CEN_NAME"
+        CEN_SVC_TYPE=
     fi
     return 0
 }
@@ -1268,14 +1326,13 @@ XDG_RUNTIME_DIR=
 
 # register option hook - adds at least --syslog
 if [ "$1" != '-A' -o -n "CEN_SVC_TYPE" ] ; then
-    CEN_SVC_HOOK_OPTIONS="$CEN_HOOK_OPTIONS"
-    CEN_HOOK_OPTIONS="_cen_svc_option"
-    CEN_SVC_HOOK_MESSAGE="$CEN_HOOK_MESSAGE"
-    CEN_HOOK_MESSAGE="_cen_svc_message"
+    context -h CEN_HOOK_OPTIONS CEN_SVC_HOOK_OPTIONS '_cen_svc_option'
+    context -h CEN_HOOK_MESSAGE CEN_SVC_HOOK_MESSAGE '_cen_svc_message'
+    context -h CEN_HOOK_QUIT    CEN_SVC_HOOK_QUIT    '_cen_svc_quithook'
 fi
 
 # the svc  module uses sysrun, remove etc
-embed -m "_centauri_bash_ext"
+embed -c "_centauri_bash_ext"
 :
 
 # end
