Work on setup, other minor changes (terminal, launcher)

diff --git a/library/_centauri_bash_iom b/library/_centauri_bash_iom
--- a/library/_centauri_bash_iom
+++ b/library/_centauri_bash_iom
@@ -887,6 +887,7 @@ configfile() {
         [ -n "$_read" ] && _cen_abort - '-a|-l|-r'
     elif [ "$_read" = '.' ] ; then                  # only -l allowed
         [ -z "$_rlin" -o -n "$_aflg" ] && _cen_abort - '-a|-r'
+        _rlin=
     elif [ -n "$_ovar" ] ; then                     # -a not allowed
         [ -n "$_aflg" ] && _cen_abort - '-a'
         [ -z "$_read" ] && _cen_abort + '-l'
@@ -898,7 +899,7 @@ configfile() {
     # error reporting
     if [ -n "$_oerr" ] ; then
         [ -z "${CEN_CONFIGFILE[2]}" ] && _cen_abort $"not in callback" '-e|-f|-w'
-        [ "${_rlin:--}" = "-" ] && _rlin="configfile"
+        [ "${_rlin:--}" = "-" ] && _rlin=$"configfile"
         if [ "$#" = 0 ] ; then
             [ -z "$_oqui" ] && set -- $"invalid statement:" "${CEN_CONFIGFILE[1]}"
         else
@@ -937,7 +938,10 @@ configfile() {
 
         if [ "$_ocom" = 2 ] ; then
             local _cen_config_lin
-            spliteval -s _cen_config_lin -- "$_line"
+            if ! spliteval -q -s _cen_config_lin -- "$_line" ; then
+                _stat=2
+                [ -z "$_oqui" ] && configfile -e - $"syntax error:" "$_line"
+            fi
             _line="$_cen_config_lin"
         elif [ -n "$_ocom" ] ; then
             local _comp
@@ -952,7 +956,7 @@ configfile() {
             local _args ; set -f
             if ! eval _args=("$_line") &>/dev/null ; then   # handle vars and quotes
                 set +f ; _stat=2
-                [ -z "$_oqui" ] && configfile -e - $"syntax error" "$_line"
+                [ -z "$_oqui" ] && configfile -e - $"syntax error:" "$_line"
             else
                 set +f ; $_read "${_args[@]}" || _stat=$?
             fi
@@ -1011,12 +1015,13 @@ configfile() {
     _file="$CEN_REDIRECT" ; CEN_CONFIGFILE[0]="$_file"
 
     # call worker
-    if [ -n "$_rlin" -o "${_read:-.}" != "." ] ; then
-        $_otra -a "configfile:" $"reading file"": $_file"
+    if [ -n "$_rlin" -o "${_read:-.}" != '.' ] ; then
+        $_otra -a -c $" read" -- "$_file"
         if [ -n "$_rlin" ] ; then
             while IFS= read -r -u $_fhan _line ; do
                 ((_lnum += 1))
-                _cen_configfile_call || break
+                _cen_configfile_call && continue
+                _stat=$? ; break
             done
         else
             [ "${#_sect[@]}" = 0 ] || _skip=1
@@ -1036,15 +1041,16 @@ configfile() {
                     _cen_configfile_fltr && continue
                 fi
                 [ -n "$_skip" ] && continue
-                _cen_configfile_call || break
+                _cen_configfile_call && continue
+                _stat=$? ; break
             done
         fi
 
     # no worker, source file...
     else
-        $_otra -a "configfile:" $"running file"": $_file"
+        $_otra -a -c $" load" -- "$_file"
         true ; . "$_file" ; _stat=$?
-        [ "$_stat" = 0 ] || error "configfile:" $"invalid data"": $_file"
+        [ "$_stat" = 0 ] || error $"Invalid data in configuration file:" "$_file"
     fi
     redirect $_oqui -s -v _fhan                             # must close handle
     return $_stat
@@ -1149,7 +1155,7 @@ serialize() {
 
         dryrun "serialize: $_ffil" && return
         create $_fqui -v _sout -h - -s -t -- "$_ffil" $_mode || return 1
-        $_otra -a -c $" writing" "$_ffil"
+        $_otra -a -c $" write" "$_ffil"
 
     # --- read ---
 
@@ -1159,7 +1165,7 @@ serialize() {
             . $_ffil &>/dev/null
             CEN_QUIT_TRAP="$_trap"
             if [ $? = 0 ] ; then
-                $_otra -a -c $" reading" "$_ffil"
+                $_otra -a -c $" read" "$_ffil"
             else
                 $_oerr $"Failed to deserialize data from:" "$_ffil"
                 return 1
