Setup improvements and fixes

diff --git a/library/_centauri_bash_sys b/library/_centauri_bash_sys
--- a/library/_centauri_bash_sys
+++ b/library/_centauri_bash_sys
@@ -78,8 +78,16 @@ CEN_SYS_EXCLUDE=("centauri*_*" "*.*" "*~" "*[ABCDEFGHIJKLMNOPQRSTUVWXYZ]*")
 CEN_SYS_OBSOLETE=()             # obsolete tool files, remove links
 CEN_SYS_SERVICE=()              # list of service tools to be installed/enabled
 CEN_PATH_REXP=()                # list of path replacements
+CEN_ROOTDEFS=()                 # see _cen_sys_rootdefs
 
-declare -a CEN_ROOT_DEF         # see sysconfig
+# ------------------------------------------------------------------------------
+# fill CEN_ROOTDEFS from CEN_INSTALL: [<rootdefs>]
+# ------------------------------------------------------------------------------
+_cen_sys_rootdefs() {
+    [ -n "$CEN_ROOTDEFS" -a "${1:--}" = '-' ] && return 0
+    embed -m '_centauri_bash_ins'
+    _cen_sys_rootdefs "$1"
+}
 
 # ------------------------------------------------------------------------------
 # get list of tools
@@ -218,7 +226,7 @@ sysversion() {
 
     # refresh data
     [ -z "$_flgo" -a -z "$_flgk" -a -z "$_flgw" ] && return 0
-    embed -m "_centauri_bash_ins"
+    embed -m '_centauri_bash_ins'
     [ -n "$_flgo" ] && _cen_ins_version -s
     [ -n "$_flgk" ] && _cen_ins_version -k
 
@@ -236,13 +244,13 @@ sysversion() {
 # ------------------------------------------------------------------------------
 # syssetup - Setup/remove folders and links and services
 #
-# Call:     syssetup [-i|-p|-r|-u] [<rootdef>|-]
+# Call:     syssetup [-i] [-r] [-s] [-n|-p|-t|-u] [<rootdef>|-]
 #
 # Options:  -i  initialize         (sysinfo install)
 #           -n  copy library files (sysinfo refresh)
 #           -p  setup paths only
 #           -r  remove, uninstall  (sysinfo uninstall)
-#           -s
+#           -s  update services    (always needs root rights)
 #           -t  check CEN_ROOT setup
 #           -u  silent update      (sysinfo update)
 #               do not configure services, no questions
@@ -251,7 +259,7 @@ sysversion() {
 #           the "defaults shared" or "defaults private" config entries in
 #           section **[library]** of **centauri-bash-lib**:
 #
-#,          <root>**:**<binaries>**:**<shortcut>**:**<repository>**:**<owner>
+#,          <root>**:**<binaries>**:**<shortcut>**:**<repository>**:**<user>**:**<group>
 #
 #+          Not all fields need to be specified, and <repository> is not
 #           interpreted by the library itself (might be used to specify a
@@ -277,7 +285,8 @@ sysversion() {
 #           command line option --info. See [[sysinfo()]] for details.
 # ------------------------------------------------------------------------------
 syssetup() {
-    local _stat=0 _warn  _remv _updt _usrv _fold="$PWD"
+    $CEN_DEBUG -c -- "$*"
+    local _stat=0 _warn  _remv _updt _usrv
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
@@ -290,64 +299,36 @@ syssetup() {
       esac ; shift
     done
 
-    # init install config is expected in CEN_ROOT_DEF
-    [ -n "$CEN_INSTALL" ] && splitjoin -s CEN_ROOT_DEF -d ':' -- "$CEN_INSTALL"
-    # override CEN_ROOT_DEF by call argument
-    if [ "${1:--}" != '-' ] ; then
-        splitjoin -s CEN_ROOT_DEF -d ':' -- "$1"
-        # <root> <bin> <link> <repo> <owner> <group>
-        if [ -n "${CEN_ROOT_DEF[5]}" ] ; then   # join to <owner>:<group>
-            CEN_ROOT_DEF[4]+=":${CEN_ROOT_DEF[5]}"
-            unset CEN_ROOT_DEF[5]
-        fi
-    fi
-
-    embed -m "_centauri_bash_ext"
-    prettypath -s CEN_ROOT_DEF[0]
-    prettypath -s CEN_ROOT_DEF[1]
-    prettypath -s CEN_ROOT_DEF[2]
-    prettypath -s CEN_ROOT_DEF[3]
+    # initial install config is expected in CEN_ROOTDEFS
+    _cen_sys_rootdefs "$1" || return 1              # also load _centaur_bash_ins
 
     if [ "$_updt" = '-n' ] ; then                   # copy library files
-        [ -w "$CEN_ROOT_DEF" ] || _warn='-w'
-        embed -m "_centauri_bash_ins" $_warn
-        _cen_ins_files "$CEN_ROOT_DEF" || _stat=$?
-        return $_stat                               # return status
-    fi
+        _cen_ins_files ; return                     # return status
+    fi || :
 
     # sysconfig, is called twice during setup as the config file may have changed
-    sysconfig "${1:+-k}"
-
-    if [ -z "$CEN_ROOT_DEF" ] ; then
-        error -z $"Unknown installation destination"
-        return 1
-    fi
-
-    set -- "${CEN_ROOT_DEF[@]::3}"
-    while [ $# -gt 0 ] ; do                     # warning if a folder is not writable
-        [ -n "$1" ] && [ ! -w "$1" ] && _warn='-w'
-        shift
-    done
-    embed -m "_centauri_bash_ins" $_warn        # CEN_LIBRARY becomes invalid
+    sysconfig "${1:+-k}" || return 1
 
     local _root="$CEN_ROOT" _base="$CEN_TOOLS" _libr="$CEN_LIBRARY"
-    CEN_ROOT="$CEN_ROOT_DEF" ; CEN_TOOLS="$CEN_ROOT/tools" ; CEN_LIBRARY="$CEN_ROOT/library"
-    splitjoin -j CEN_INSTALL -d ':' -i CEN_ROOT_DEF
+    CEN_ROOT="$CEN_ROOTDEFS" ; CEN_TOOLS="$CEN_ROOT/tools" ; CEN_LIBRARY="$CEN_ROOT/library"
+    splitjoin -j CEN_INSTALL -d ':' -i CEN_ROOTDEFS
     $CEN_TRACE -a $"Installation configuration:" "$CEN_INSTALL"
 
-    _cen_ins_library $_remv $_updt $_usrv       # run update/install
-    _stat=$? ; [ "$_stat" = 128 ] && return 128 # cancelled
+    {   _cen_ins_library $_remv $_updt $_usrv       # run update/install
+        _stat=$? ; [ "$_stat" = 128 ] && return 128 # cancelled
+    } || :
 
     if [ -z "$_remv" -a "$_updt" != "-t" ] ; then
-        folder -c -f "/"                        # don't block CEN_ROOT
-        if [ -n "$_updt" ] ; then               # update only (see centauriconfig)
+        local _fold="$PWD"
+        folder -c -f '/'                            # don't block CEN_ROOT
+        if [ -n "$_updt" ] ; then                   # update only (see centauriconfig)
             sysconfig -u
         else
             sysversion -u ; sysconfig -c -p -s
         fi
-    fi
+        folder -c -q -- "$_fold"                    # restore saved folder
+    fi || :                                         # ignore errors
 
-    folder -c -q -- "$_fold"                    # restore saved folder
     CEN_ROOT="$_root" ; CEN_TOOLS="$_base" ; CEN_LIBRARY="$_libr"
     return $_stat
 }
@@ -357,8 +338,7 @@ syssetup() {
 #
 # Call:     (1) sysinfo [**version**|**detailed**]
 #           (2) sysinfo [**install**|**uninstall**|**update**] <root> [**noquit**]
-#           (3) cd <repo>
-#               sysinfo **refresh**|**setup** <dest> [**noquit**]
+#           (3) sysinfo **refresh**|**setup** <repo>|- <dest>|- [**noquit**]
 #
 #+General:  This is the implementation of command line option **--info**. The sysinfo
 #           function is invoked from option processsing in [[main()]]. It should not be
@@ -383,10 +363,12 @@ syssetup() {
 #           <repo>        § origin (probably the current CEN_ROOT)
 #           <root>        § override defaults, see [[syssetup]]
 #
-#+Unless **noquit** is specified (form (2) and form (3) only), the function calls
-# [[quit()]] and never returns.
+#+All arguments other than "version" and "detailed" invoke [[syssetup()]]. Unless
+# **noquit** is specified (form (2) and form (3) only), the function calls [[quit()]]
+# and never returns.
 # ------------------------------------------------------------------------------
 sysinfo() {
+    $CEN_DEBUG -c -- "$*"
     local _dopt _iopt _fnoq _stat=0
     # help should not advertise the 'detailed' command
     local _cmds='help install paths refresh setup uninstall update version'
@@ -414,6 +396,12 @@ sysinfo() {
         done
         quit
     elif [ -n "$_iopt" ] ; then                     # setup actions
+        if [ "$_iopt" = '-n' ] ; then
+            [ -z "$2" ] && fatal $"Missing argument:" '<repo>'
+            [ -z "$3" ] && fatal $"Missing argument:" '<dest>'
+            [ "$2" = '-' ] && set -- "$1" "$CEN_ROOT" "$3" "$4"
+            folder -f -- "$2" ; set -- "$1" "$3" "$4"
+        fi
         syssetup $_iopt -- "$2" || _stat=$?
         [ "$3" = 'noquit' ] && return $_stat
         case $_stat in
@@ -441,24 +429,25 @@ sysinfo() {
 }
 
 # ------------------------------------------------------------------------------
-# sysconfig - read library config, generate bash_completion and proxy
+# sysconfig - read library config, generate bash completion and proxy
 #
 # Call:     sysconfig [-c|-p]
 #
 # Options:  -c  generate bash completion
-#           -k  keep CEN_ROOT_DEF unchanged
-#           -p  generate proxy
+#           -k  keep CEN_ROOTDEFS unchanged (internal use by syssetup)
+#           -p  generate the centauri-bash-lib proxy
 #           -s  check if systemd is to be used
 #           -u  update if neccessary
 #
-# Reads **$CEN_ROOT/default/centauri_bash_lib** (for Debian this path is equal
-# to **/etc/default/centauri_bash_lib**). If the file exists, it overrides the
-# built-in default configuration.
+#+Reads the **[library]** section of **$CEN_ROOT/default/centauri_bash_lib**
+# (for Debian this path is equal to **/etc/default/centauri_bash_lib**).
+# Configuration file data overrides the built-in default configuration.
 #
-# Optionally **_centauri_bash_completion** and the **_centauri_bash_lib** proxy
+#+Optionally **_centauri_bash_completion** and the **_centauri_bash_lib** proxy
 # can be generated.
 # ------------------------------------------------------------------------------
 sysconfig() {
+    $CEN_DEBUG -c -- "$*"
 
     # --- get config ---
 
@@ -491,7 +480,9 @@ sysconfig() {
                        else
                            configfile -w "sysconfig" ; return 0
                        fi
-                       shift ; [ -z "$_kopt" ] && CEN_ROOT_DEF=("$@")
+                       [ -n "$_kopt" ] && return 0
+                       splitjoin -j _skey -d ':' -- "${@:2}"
+                       _cen_sys_rootdefs "$_skey"
                        ;;
             repath )   configfile -w "sysconfig" 3 + $#
                        trimjoin -d $'\a' -- "$@" ; CEN_PATH_REXP+=("$CEN_TRIMJOIN")
@@ -586,7 +577,7 @@ complete -X "@(.[^/]*|./.*)" -F _centauri_bash_lib_compl $_tool
       esac ; shift
     done
 
-    embed -m "_centauri_bash_run"                           # load _centauri_bash_iom
+    embed -m '_centauri_bash_run'                           # load modules ext/iom/run
 
     local _pcfg="$CEN_ROOT/centauri-bash-lib"
     if [ -f "$_pcfg" ] ; then
@@ -601,8 +592,8 @@ complete -X "@(.[^/]*|./.*)" -F _centauri_bash_lib_compl $_tool
     [ -n "$_popt" -a -d "$CEN_TOOLS" ] && _cen_run_proxy    # generate proxy
 
     if [ -n "$_copt" -a -d "$CEN_LIBRARY" ] ; then          # bash completion
-        _cen_sys_tools
-        _cen_sys_completion "${CEN_SYS_TOOLS[@]}"
+        _cen_sys_tools || _stat=$?
+        _cen_sys_completion "${CEN_SYS_TOOLS[@]}" || _stat=$?
     fi
 
     if [ -n "$_sopt" ]  ; then
@@ -617,7 +608,8 @@ complete -X "@(.[^/]*|./.*)" -F _centauri_bash_lib_compl $_tool
         else
             folder -m "$CEN_ROOT/systemd"
         fi
-    fi
+    fi || _stat=$?
+    return $_stat
 }
 
 # ------------------------------------------------------------------------------
