added sysloop(), cleanups and fixes, documentation

diff --git a/library/_centauri_bash_ext b/library/_centauri_bash_ext
--- a/library/_centauri_bash_ext
+++ b/library/_centauri_bash_ext
@@ -162,7 +162,7 @@ _cen_path_realp() {
             if [ -n "$CEN_FEATURE_A" ] ; then
                 # set cache and flag if builtin can be loaded
                 if _cen_dyn_builtin 'realpath' >/dev/null ; then
-                    CEN_CMD_PATH['realpath']='-' ;CEN_EXT_REALP=1
+                    CEN_COMMANDS['realpath']='-' ;CEN_EXT_REALP=1
                 fi
             fi
             _cen_path_realp "$@"
@@ -175,12 +175,12 @@ _cen_path_realp() {
         [ "$CEN_VERB" -gt 1 ] && dryrun -r "builtin" "${_exro[@]}"
         builtin "${_exro[@]}" &>/dev/null && _retr=0
     else
-        sysrun -a _rslt -b -q -r "${_exro[@]}" -- "$2" && _retr=0
+        sysrun -q -r -a _rslt -b "${_exro[@]}" -- "$2" && _retr=0
     fi
 
     # retry with readlink -m as fallback
     if [ "$_retr" = 1 ] ; then
-        sysrun -a _rslt -b -q -r -- readlink -m -- "$2" && _retr=0
+        sysrun -q -r -a _rslt -b -- readlink -m -- "$2" && _retr=0
     fi
 
     if [ "$_retr" = 0 ] ; then                  # success: set _logi
@@ -513,11 +513,11 @@ listsearch() {
 # <dest> must be a folder. In this case -o and -x are disabled.
 # ------------------------------------------------------------------------------
 move() {
-    local _oftl _orep _orun _osys="-p" _oerr=error _omsg="$CEN_TRACE"
+    local _oftl _orep _orun _osys="-e -p" _oerr=error _omsg="$CEN_TRACE"
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
-      -f)   _oftl="-f" ; _oerr=fatal ;;
+      -f)   _oftl="-f" ; _osys="-f -p" ; _oerr=fatal ;;
       -o)   _orem=1 ;;
       -q)   _orep="-q" ; _osys="-q" ; _oerr="$CEN_TRACE" ;;
       -r)   _orun="-r" ;;
@@ -551,7 +551,7 @@ move() {
 
     $_omsg -a -p $"Moving '%s' to '%s'" "${*:1:$#-1}" "$_dest"
 
-    sysrun $_oftl $_orun $_osys -b -- mv -f -- "${@:1:$#-1}" "$_dest" && return 0
+    sysrun $_orun $_osys -b -- mv -f -- "${@:1:$#-1}" "$_dest" && return 0
     [ -n "$CEN_OPT_DRYRUN" ]                     # --dryrun always returns 0
 }
 
@@ -807,15 +807,12 @@ prettypath() {
 
     if [ "$_ocan" = 1 ] ; then                      # read symlink
         _cen_path_realp -l "$1" && _varg="$_logi"
-        # sysrun -r -q -b -a _logi -- readlink -s -- "$1" && _varg="$_logi"
     elif [ -n "$_ocan" ] ; then                     # canonicalize
         _cen_path_realp -c "$1" && _varg="$_logi"
-        # sysrun -r -q -b -a _logi -- readlink -s -m -- "$1" && _varg="$_logi"
     else                                            # prettify
         _cen_path_pretty -p "$_fset" "$1"
         if [[ "$_varg" == *..* ]] ; then            # must canonicalize path ...
             _cen_path_realp -a "$1" && _varg="$_logi"
-            # sysrun -r -q -b -a _logi -- readlink -s -m -- "$1" && _varg="$_logi"
         fi
     fi
 
@@ -1045,12 +1042,12 @@ remove() {
 # function fails if <des> exists and neither option -o or -x are given.
 # ------------------------------------------------------------------------------
 rename() {
-    local _oftl _omis _orep _orun _osys="-p" _oerr=error _omsg="$CEN_TRACE" _suff
+    local _oftl _omis _orep _orun _osys="-e -p" _oerr=error _omsg="$CEN_TRACE" _suff
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -b)   shift ; _suff="$1" ; _orem=1 ;;
-      -f)   _oftl="-f" ; _oerr=fatal ;;
+      -f)   _oftl="-f" ; _osys="-f -p" ; _oerr=fatal ;;
       -m)   _omis=1 ;;
       -o)   _orem=1 ;;
       -q)   _orep="-q" ; _osys="-q" ; _oerr="$CEN_TRACE" ;;
@@ -1089,7 +1086,7 @@ rename() {
     fi
 
     $_omsg -a -p $"Renaming '%s' to '%s'" "$1" "$_dest"
-    sysrun -b $_oftl $_orun $_osys -- mv -f -- "$1" "$_dest" && return 0
+    sysrun -b $_orun $_osys -- mv -f -- "$1" "$_dest" && return 0
     [ -n "$CEN_OPT_DRYRUN" ]                     # --dryrun always returns 0
 }
 
@@ -1107,7 +1104,7 @@ rename() {
 #           -s  save result to <var>
 #           -t  trim prefix from result paths
 #           -f  make errors fatal
-#           -p  return pretty name, [[see prettypath()]]
+#           -p  return pretty name, see [[prettypath()]]
 #           -q  do not report errors
 #           -x  locate an executable file using BASH_ARGV0
 #           -y  locate a file using BASH_ARGV0
@@ -1147,7 +1144,7 @@ rename() {
 # ------------------------------------------------------------------------------
 CEN_RESOLVE=
 resolve() {
-    local _ocan _otrm _oerr="-e" _oexe _oftl _pret \
+    local _ocan _otrm _oexe _osys='-e -p' _pret \
           _vset="CEN_RESOLVE" _varr _vrrr _xchk _xerr=error _nret=0
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
@@ -1155,10 +1152,10 @@ resolve() {
       -a)   shift ; _vset= ; local -n _vvaa="$1" ; _vvaa=() ;;
       -c)   _ocan='-e' ;;
       -e)   _xchk=1 ;;
-      -f)   _xerr=fatal ; _oftl="-f" ;;
+      -f)   _xerr=fatal ; _osys="-f -p" ;;
       -m)   _ocan='-m' ;;
       -p)   _pret=1 ;;
-      -q)   _xerr=: ; _oftl="-q" ;;
+      -q)   _xerr=: ; _osys="-q" ;;
       -s)   shift ; _vset="$1" ; _varr= ;;
       -t)   shift ; _otrm="$1" ;;
       -x)   _oexe=1 ;;
@@ -1175,7 +1172,7 @@ resolve() {
     # get executable - use _centauri_bash_lib paths and resolve argv0 if needed
     if [ -n "$_oexe" ] ; then
         local _logi _self="$CEN_TOOLS:$CEN_LIBRARY:${BASH_ARGV0%/*}"
-        PATH="$PATH:$_self" sysrun -a _logi -q -r -s -- type -f -p -- "$1"
+        PATH="$PATH:$_self" sysrun -q -r -s -a _logi -- type -f -p -- "$1"
         if [ -z "$_logi" ] ; then
             [ -h "$BASH_ARGV0" ] && _cen_path_realp -c "$BASH_ARGV0"
             _self="${_logi%/*}"
@@ -1211,7 +1208,7 @@ resolve() {
                 _cen_path_realp -c "$1" || return 1 ; set -- "$_logi"
             fi
         elif [ $# -gt 1 ] ; then
-            sysrun $_oftl -a _vrrr -r $_oftl -- readlink $_ocan -- "$@" || return 1
+            sysrun $_osys -a _vrrr -r -- readlink $_ocan -- "$@" || return 1
             set -- "${_vrrr[@]}"
         fi
     fi
@@ -1221,7 +1218,7 @@ resolve() {
         _vrrr=()
         for _logi in "$@" ; do
             if [ -n "$_pret" ] ; then
-                _cen_path_pretty $_oerr -p _logi "$_logi" || continue
+                _cen_path_pretty -e -p _logi "$_logi" || continue
             fi
             [ -n "$_otrm" ] && _cen_path_ltrim "$_otrm"
             _vrrr+=("$_logi")
@@ -1321,7 +1318,7 @@ splitpath() {
     esac
 
     if [[ "$_path" == *..* ]] ; then            # must canonicalize path ...
-        sysrun -r -q -b -a _path -- readlink -s -m -- "$1" || return 2
+        sysrun -q -r -b -a _path -- readlink -s -m -- "$1" || return 2
     fi
 
     [ "$_path" = '/' ] && return 1              # root has no parent
@@ -1474,9 +1471,12 @@ suffixpath() {
 }
 
 # ------------------------------------------------------------------------------
-# symlink - Make a symlink to a target using /usr/bin/ln
+# symlink - Make symlink single or multiple targets using /usr/bin/ln
 #
-# Call:      symlink [-r|-q] [-m] [-s] [--] <target> [<link>]
+# Call:     (1) symlink [-f|-q] [-i] [-n] [-m|-x] [-r] [-s] [--] <target> <link>
+#           (2) symlink [-f|-q] [-i] [-n] [-m|-x] [-r] [-s] [--] <target> [<fldr>]
+#           (3) symlink [-f|-q] [-n] [-r] [--] <target>... <fldr>
+#           (4) symlink -n [-f|-q] [-r] [-s] [--] <target> <fldr>/<link>
 #
 # Options:  -c  canonicalize target path
 #           -d  allow that <link> is a folder
@@ -1491,11 +1491,21 @@ suffixpath() {
 #
 #           [*] these options allow the creation of stale symlinks
 #
+# Arguments:<target> location the symlink points to
+#           <link>   name (or path) of symlink to be created
+#           <fldr>   folder where to create the symlink
+#
 # Return:   **0** := OK   **1** := no <target>   **2** := <link> is a file
 #
-#+This is a conveniency wrapper for **/usr/bin/ln** that provides some extra
-# reporting and error handling. Without option -n the function refuses to create
-# a ''symlink'' if <target> does not exist.
+#+This is a conveniency wrapper for **/usr/bin/ln** (or the loadable bash builtin)
+# that provides some extra reporting and error handling. Without option -n the
+# form (1) and (2) refuse to create a ''symlink'' if <target> does not exist.
+#
+#+Form (3) can place multiple links into a folder but cannot check <target>...
+# at all.
+#
+#+The function cannot check a relative <target> path with <link> being a folder,
+# see form (4).
 # ------------------------------------------------------------------------------
 symlink() {
     local _fign _targ _ocan _odir _oftl='error' _onck _orel _osys='-e -p' _move _mesg="$CEN_TRACE"
@@ -1518,6 +1528,14 @@ symlink() {
     done
     local _etxt _link="$2" _targ="$1"
 
+    # multiple targets, link must be a folder, run /usr/bin/ln
+    if [ $# -gt 2 ] ; then
+        local _leng="$#" ; _link="${!_leng}"    # kde/kate highligt bug: "${!#}"
+        folder ${_osys//-[ep]/} -- "$_link" || return 1
+        sysrun $_osys -i -m "$_etxt" -d -- ln $_onck $_orel -s -- "$@" || return 1
+        return
+    fi
+
     if [ -z "$_link" ] ; then
         _link="${_targ##*/}"
     elif [ -n "$_odir" ] && [ -d "$_link" ] ; then
@@ -1531,7 +1549,7 @@ symlink() {
         elif [ "$_targ" -ef "$_link" ] ; then
             $_mesg -a $"Target '$_targ', link is current"": $_link" ; return 0
         else
-            [ -n "$_ocan" ] && system -r -q -s _targ -- readlink -s -m -- "$_targ"
+            [ -n "$_ocan" ] && _cen_path_realp -c "$_targ" && _targ="$_logi"
         fi
 
         if [ -h "$_link" ] ; then
@@ -1563,41 +1581,50 @@ symlink() {
 }
 
 # ------------------------------------------------------------------------------
-# sysrun - generate messages for errors, optionally run a command
+# sysrun - run a command or builtin, optionally generate error messages
 #
-# Call:     (1) sysrun [-f] [-m <mesg>] -c <stat> [--] [<cmd> <arg>...]
-#           (2) sysrun [-f|-q] [-a <anam>] [-m <mesg>] [-b|-n]
-#                      [-d] [-p] [-r] [-s] [--] <cmd> <arg>...
+# Call:     (1) sysrun [-e|-f] [-p] [-m <mesg>] [-w <what>]
+#                      [-a <anam>] [-b|-i] [-d] [-n] [-r] [-z] [--] <cmd> <arg>...
+#           (2) sysrun -q
+#                      [-a <anam>] [-b|-i] [-d] [-n] [-r] [-z] [--] <cmd> <arg>...
+#           (3) sysrun -c <stat> [-f] [-m <mesg>] [--] [<cmd> <arg>...]
 #
-# Options:  -a  capture output into an array
-#           -b  do not run a script function, prefer builtin over command
+#+          This is a faster, simpler variant of [[system()]], see below. Form (1)
+#           runs a command or builtin with error reporting, form (2) does no error
+#           reporting at all. Form (3) can be used to generate error messages from
+#           error codes.
+#
+# Options:  -a  capture **/dev/stdout** into an array (overrides -p and -q)
+#           -b  do not run a function, prefer builtin over external
 #           -c  error code for reporting (<cmd> is not executed)
 #           -d  use './' prefix if 1st arg starts with a '-'
-#           -e  ignored for [[system()]] compatibility
-#           -f  make errors fatal
-#           -i  do not run a script or builtin, see **sysfind -i**
-#           -m  format string for error message
+#           -e  print error message if command <cmd> fails
+#           -f  like -e but make errors fatal
+#           -i  do not run a function or builtin, see **sysfind -i**
+#           -m  custom format string for error message
 #           -n  do no checks on <cmd> (implied if <cmd> is a path)
-#           -p  pretty-print error messages
-#           -q  do not output error messages
+#           -p  discard **/dev/stdout**, capture **/dev/stderr**, pretty-print error message
+#           -q  discard **/dev/stdout** and **/dev/stderr**, no error message
 #           -r  ignore --dryrun
-#           -s  do not report activity via [[trace()]]
-#           -z  don't capture **/dev/stdout**, but -a and -p capture **/dev/stderr**
+#           -s  **DO NOT USE**
+#           -w  override command name in error message
+#           -z  don't capture **/dev/stdout** (for use with -p)
 #
 # Arguments:<mesg>  printf format string with 2 string variables
+#           <what>  shown in error message
 #           <stat>  status code to report (**0** reports nothing)
 #           <cmd>   a program name or path
 #           <arg>   program argument, at least one argument is required
 #
 # Return:   **true** at success or **false** otherwise.
 #
-#+This function can be used (1) to create error messages or (2) to run a command -
-# optionally reporting errors. It is much simpler than [[system()]] and uses a
-# temporary file to catch the program output (or error messages).
+#+The options -e -f -p -q and -z of this function work like in [[system()]].
+# The use of -c -m and -w offers extra functionality for error reporting.
+# The main reason for using sysrun is performance:
 #
 #+The bash "$(<cmd>°<arg>...)" construct as it is used by [[system()]] creates a
-# subshell for each command, which is time consuming and spawns extra processes.
-# On the other hand the temporary file used by [[sysrun()]] has to be created on
+# subshell for each command, which is time consuming and can spawn extra processes.
+# On the other hand the temporary file used by sysrun has to be created on
 # 1st use and later to be deleted in a quit hook, see [[quit()]].
 #
 #+So this function is good especially when builtin commands like **mkdir**, **rmdir**,
@@ -1649,23 +1676,23 @@ symlink() {
 # ------------------------------------------------------------------------------
 sysrun() {
     $CEN_NOTRACE set +x
-    local _ecmd=error _emsg _ofmt _oign _osta _opre _orun _oout=0 _owho _ffnd=1 _vnam _tcmd="$CEN_TRACE"
+    local _ecmd="$CEN_TRACE" _emsg _ofmt _oign _osta _opre _orun _oout _owho _ffnd=1 _vnam
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
-      -a)   shift ; _vnam="$1" ;;
+      -a)   shift ; _vnam="$1" ; _oout=0 ;;
       -b)   _ffnd=0 ;;
       -c)   shift ; _osta="$1" ;;
       -d)   _opre=1 ;;
-      -e)   ;;
+      -e)   _ecmd=error ;;
       -f)   _ecmd=fatal ;;
       -i)   _oign='-i' ;;
-      -m)   shift ; _emsg="$1" ;;
+      -m)   shift ; _emsg="$1" ; [ -z "$_oout" ] && _oout=0 ;;
       -n)   _ffnd= ;;
-      -p)   _ofmt=1 ;;
-      -q)   _ecmd= ;;
+      -p)   _ofmt=1 ; [ -z "$_oout" ] && _oout=0 ;;
+      -q)   [ -z "$_oout" ] && _oout=0 ;;
       -r)   _orun="-r" ;;
-      -s)   _tcmd=":" ;;
+#      -s)   ;;
       -w)   shift ; _owho="$1" ;;
       -z)   _oout=1 ;;
       *)    _cen_abort - "$1"
@@ -1684,7 +1711,7 @@ sysrun() {
             _opre=
         # using sysfind and cache
         else
-            _xtmp="${CEN_CMD_PATH["$_xcmd"]}"               # sysfind() cache
+            _xtmp="${CEN_COMMANDS["${_xcmd:--}"]}"          # sysfind() cache
             if [ "$_xtmp" = '-' ] ; then                    # cached as builtin
                 if [ -z "$_oign" ] ; then
                     _xtmp="$_xcmd"
@@ -1717,7 +1744,6 @@ sysrun() {
 
     # run command "$_xcmd" ...
     if [ -z "$_osta" ] ; then
-        [ "$_tcmd" = ":" ] && _orun+=" -s"
 
         # stupid builtins: remove '--' from command line
         if [ -n "$_opre" ] ; then
@@ -1749,7 +1775,7 @@ sysrun() {
             IFS=$'\n' read -a "${_vnam:-_xerr}" -d '' -r <"$_outf"
         elif [ "$_oout" = 0 ] ; then
             "$_xcmd" "$@" &>/dev/null ; _osta=$?
-        elif [ "$_oout" = 1 ] ; then
+        else
             "$_xcmd" "$@" ; _osta=$?
         fi || :
     fi
@@ -1768,19 +1794,23 @@ sysrun() {
                 _xmsg=$"Status"" $_osta"
             fi
     esac
-    [ "$_tcmd" = ":" ] || _tcmd+=" -a"
-    [ "${_emsg:--}" = "-" ] && _emsg=$"Running '%s%s' failed"
+
+    [ "${_emsg:--}" = '-' ] && _emsg=$"Running '%s%s' failed"
     [ -n "$_xmsg" ] && _xmsg=": $_xmsg"
-    if [ -n "$_ofmt" ] ; then                           # system() style ...
+    if [ -z "$_ecmd" -a -n "$_ofmt" ] ; then            # system -p style
+        splitjoin -j _xtmp -d '\n' -i "${_vnam:-_xerr}"
+        message -m "$_xtmp"
+        $CEN_NOTRACE set -x ; return $_osta
+    elif [ -n "$_ofmt" ] ; then                         # system -e -p style
         splitjoin -s _xtmp -d '\n' -i "${_vnam:-_xerr}"
         _xarg=
         for _xtmp in "${_xtmp[@]}" ; do
             _xarg+="${_xtmp#/*: *: }"$'\n'              # strip bash error prefix
         done
-        ${_ecmd:-$_tcmd} -m -p "${_emsg} %s\n%s" "${_owho:-($_xcmd)}" "" "$_xmsg" "$_xarg"
+        $_ecmd -m -p "${_emsg} %s\n%s" "${_owho:-($_xcmd)}" "" "$_xmsg" "$_xarg"
     else                                                # simple ...
-        [ $# -gt 0 ] && _xarg=" $*"
-        ${_ecmd:-$_tcmd} -p "$_emsg$_xmsg" "${_owho:-($_xcmd)}" "$_xarg"
+        # [ $# -gt 0 ] && _xarg=" $*"
+        $_ecmd -p "$_emsg$_xmsg" "${_owho:-($_xcmd)}" "$_xarg"
     fi
     $CEN_NOTRACE set -x ; return $_osta
 }
@@ -1930,7 +1960,7 @@ tmpfile() {
         [ -d "$_base" ] && return 0                     # don't remove folder
         set +f ; set -- "$_base$_ssuf"*                 # make sure glob is on
         [ "$1" = "$_base$_ssuf*" ] && return 0          # nothing to remove
-        sysrun -b -q -- rm -f -- "$@" ; return          # return status
+        sysrun -q -b -- rm -f -- "$@" ; return          # return status
     fi
 
     # create folder / file
@@ -1957,7 +1987,7 @@ tmpfile() {
         2>/dev/null >"$_svar" && return 0
         $_oerr $"Cannot create" "$_svar" || return 1
     else
-        sysrun -b -e $_orun -- mkfifo "$_svar" || return 1
+        sysrun -e -b $_orun -- mkfifo "$_svar" || return 1
     fi
     return 0
 }
@@ -2086,6 +2116,7 @@ trimjoin() {
 CEN_WALK_FILES=()
 CEN_WALK_DIRS=()
 CEN_WALK_LEVEL=0
+declare -g -A CEN_WALK_DMAP
 
 walk() {
     local _fdir=false _ffil=: _fexc=: _frec _fadd _fbro="-e" _fhid _fext=() _stat _levl=999999999
@@ -2137,13 +2168,12 @@ walk() {
 
         # recurse into folders
         if [ -n "$_dirs" -a "$_stat" -lt 3 ] ; then
-            local _full _indx=0 _exe_dirn
-            sysrun -r -p -a _exe_dirn -b -- readlink -m -- "${_dirs[@]}" || return 3
+            local _full _indx=0 _cen_walk_dirn
+            resolve -a _cen_walk_dirn -m -- "${_dirs[@]}" || return 3
             for _item in "${_dirs[@]}" ; do
-                _full="${_exe_dirn[_indx++]}"
+                _full="${_cen_walk_dirn[_indx++]}"
                 [ -n "${CEN_WALK_DMAP[$_full]}" ] && continue
                 CEN_WALK_DMAP[$_full]="$_item"
-
                 _stat=0
                 if [ "$_ffil" = "false" ] ; then  # --incl/--excl
                     $_fexc "${_full##*/}" ; _stat=$?
diff --git a/library/_centauri_bash_pip b/library/_centauri_bash_pip
--- a/library/_centauri_bash_pip
+++ b/library/_centauri_bash_pip
@@ -4,35 +4,44 @@
 #
 # Call:     . _centauri_bash_pip
 #
-#+General:  The module implements three functions that use pipes (fifo) or
+#+General:  The module implements four functions that use pipes (fifos) or
 #           the bash coproc command:
 #
 #,          - [[sysbind()]]  - bind two pipes to a server process, simple RPC calls
 #,          - [[syspager()]] - pipe a command's output through a pager (like less)
 #,          - [[syspipe()]]  - run a command in background using coproc or a pipe
+#,          - [[sysloop()]]  - implements an event loop using a pipe
 #
 # Copyright Dr. J. Pfennig (c) 2021-2022
 # ------------------------------------------------------------------------------
 
 CEN_MODULES['_centauri_bash_pip']='0.02:1'
 
+CEN_PIP_BUSY=                   # coproc recursion protection
+CEN_PIP_QUIT=                   # quit hook, see piploop()
+CEN_PIP_BMAP=                   # dictionary of sysbind instances
+
+embed -c '_centauri_bash_ext'           # import on demand
+
 # ------------------------------------------------------------------------------
 # Pager + Using a pager like less or more
 #
 #+The library supports a pager via the [[_centauri_bash_pip]] module. If this
 # module is available at script start time, the option --pager gets enabled
-# automatically and all output from [[run()]] or action handlers can be passed
-# through a pager this way.
+# automatically and all output from [[run()]], action handlers or [[usage()]]
+# can be passed through a pager this way.
 #
 #+The easiest method for paging output programmatically (and thereby honoring
 # the --pager option) is using the CEN_PAGER variable. On request the option
-# parser in [[main()]] will load [[_centauri_bash_pip]] and call [[syspipe()]]:
+# parser in [[main()]] will load [[_centauri_bash_pip]] and call [[syspipe()]].
+# The [[syspipe()]] call will set "CEN_PAGER=syspipe" if paging is enabled,
+# or clear CEN_PAGER if paging is off:
 #
 #.      $CEN_PAGER <worker> <arg>...
 #
-#+The [[syspipe()]] call will set "CEN_PAGER=syspipe" if paging is enabled,
-# or clear CEN_PAGER if paging is off. To enable paging when --pager is not
-# set, use the following code:
+#+The library functions [[main()]] and [[usage()]] use $CEN_PAGER internally
+# to pass their output to a pager. To enable paging without --pager being set,
+# use the following code:
 #
 #.      embed -q _centauri_bash_pip && syspipe  # load module and enable
 #.      $CEN_PAGER <worker> <arg>...
@@ -48,16 +57,19 @@ CEN_MODULES['_centauri_bash_pip']='0.02:1'
 # to prettify it.
 # ------------------------------------------------------------------------------
 
-embed -c '_centauri_bash_ext'           # import on demand
-
-CEN_PIP_BUSY=                           # coproc recursion protection
-
 # ------------------------------------------------------------------------------
 # sysbind - bind two pipes to an external server process, simple RPC calls
 #
-# Call:     sysbind [-e|-f] [-i <inst>] -s [-d <data>] [--] <serv> <arg>...
-#           sysbind [-e|-f] [-i <inst>] -c [<name>|-] [-a <rslt>] [-d <data> | [--] <arg>...]
-#           sysbind [-e|-f] [-i <inst>] -t
+# Call:     (1) sysbind [-e|-f] [-i <inst>] -s [-d <data>] [--] <serv> <arg>...
+#           (2) sysbind [-e|-f] [-i <inst>] -c [<name>|-] [-a <rslt>] [-d <data> | [--] <arg>...]
+#           (3) sysbind [-e|-f] [-i <inst>] -t
+#
+#           *** NOT YET IMPLEMENTED ***
+#
+#+          Form (1) starts one server process per instance, see <inst>. The server
+#           **/dev/stdin** and **/dev/stdout** are connected via pipes to this
+#           sysbind instance. Form (2) does a simple RPC call and (3) terminates
+#           the server and closes the instance.
 #
 # Options:  -a  destination array for RPC reply
 #           -i  array to keep state in (default: CEN_SYSBIND)
@@ -65,14 +77,16 @@ CEN_PIP_BUSY=                           # coproc recursion protection
 #           -d  send data to server
 #           -e  report errors
 #           -f  errors are fatal
-#           -s  open pipes (start server)
+#           -s  open pipes (start server process)
 #           -t  close pipes (terminate server)
 #
 # Arguments:<arg>   arguments for server
 #           <inst>  instance array, not to be modified by caller
 #           <rslt>  array to receive server reply
 #
-# Instance: An array managed by this function, not to be modified by caller
+# Return:   **true** at success or **false** otherwise.
+#
+#+Instance: An array managed by this function, not to be modified by caller
 #
 #,          inst[0]     process id of server
 #,          inst[1]     handle for send pipe
@@ -81,12 +95,17 @@ CEN_PIP_BUSY=                           # coproc recursion protection
 #,          inst[4]     receive fifo name (if any)
 #,          ...         opaque data for internal use
 #
-# Return:   **true** at success or **false** otherwise.
+#+          Using multiple instace arrays allow the use of multiple, independent
+#           servers.
 #
-#+The RPC protocol should be text-line based (server replies are split into
-# lines, delimiter is "\n"). The server must only send data in reply to a
-# request. On each request a reply must be send. Server replies must end with
-# a "\n".
+#+Protocol: The RPC protocol should be text-line based (server replies are split
+#           into lines, delimiter is "\n"). The server must only send data in
+#           reply to a request. On each request a reply must be sent. Server
+#           replies must end with a "\n".
+#
+#+          To terminate a server instance, option -t sends a SIGHUP signal before
+#           closing the pipes. On the client side syspipe registers a quit hook
+#           that terminates all servers via SIGHUP.
 # ------------------------------------------------------------------------------
 CEN_SYSBIND=
 sysbind() {
@@ -97,7 +116,7 @@ sysbind() {
       --)   shift ; break ;;
       -a)   shift ;;
       -i)   shift ; _inam="$1" ;;
-      -c)   shift _frun=2;;
+      -c)   shift ; _frun=2;;
       -d)   shift ;;
       -e)   _emsg='error' ;;
       -f)   _emsg='fatal' ;;
@@ -108,25 +127,54 @@ sysbind() {
     done
     [ -z "$_frun" ] && _cen_abort + '-s|-c|-t'
 
+    # sysbind -i * is used to ternate all instances
+    if [ "$_inam" = '*' ] ; then
+        [ "${#CEN_SYSBIND[*]}" -le 1 ] && return 0
+        trace "sysbind terminate all instances"
+        for _frun in "${!CEN_PIP_BMAP[@]}" ; do
+            sysbind -t "$_frun"
+        done
+        return 0
+    fi
+
     local -n _inst="$_inam"
 
     # close pipes, terminate server
     if [ "$_frun" = 0 ] ; then
         [ -z "$_inst" ] && return 0                     # not initialized
-        _inst=()
+        _inst=('-')
 
     # open pipes, start server
     elif [ "$_frun" = 1 ] ; then
-        if [ -n "$_inst" ] ; then                       # already initialized
-            _emsg -- $"server already initialized" ; return 1
+        if [ "${_inst:--}" != '-' ] ; then              # already initialized
+            _emsg -- $"sysbind instance already running:" "$_inam" ; return 1
         fi
+
+        # manage a map of instances
+        if [ "${#CEN_SYSBIND[*]}" -le 1 ] ; then
+            unset CEN_PIP_BMAP
+            declare -g -A CEN_PIP_BMAP ; CEN_SYSBIND=('-')
+        fi
+        CEN_PIP_BMAP["$_inam"]="$_inam"
+        declare -p CEN_PIP_BMAP
+
         _inst=(- - - - -)
-        fatal "not implemented"
+        #fatal "not implemented"
+        if [ -z "$CEN_PIP_QUIT" ] ; then
+            CEN_PIP_QUIT="$CEN_HOOK_QUIT"
+            CEN_HOOK_QUIT=_cen_pip_quit
+        fi
+
+        # manage an array of instances
+        #[ "${#CEN_SYSBIND[*]}" = 0 ] && CEN_SYSBIND=(- - - - -)
+        #CEN_SYSBIND+=("$_inam")
+
+        # TODO: context -t +/-
 
     # call server
     else
         if [ -z "$_inst" ] ; then                       # not initialized
-            _emsg -- $"server not initialized" ; return 1
+            _emsg -- $"sysbind instance not running:" "$_inam" ; return 1
         fi
         fatal "not implemented"
     fi
@@ -488,5 +536,205 @@ syspipe() {
     [ "${_ocal:--}" != '-' -a "$_stat" != 0 ] && $_ocal 'STATUS' "$_stat" "$_acmd"
     return $_stat
 }
+
+# ------------------------------------------------------------------------------
+# sysloop - implements an event loop using a pipe
+#
+# Call:     (1) sysloop [-e|-f] [-c <evnt>] [-p <pipe>]
+#           (2) sysloop [-e|-f] [-c <evnt>] -t <time> [-p <pipe>] [--] [<tick>]
+#           (3) sysloop [-e|-f] -m [-p <pipe>] [--] <mesg>...
+#           (4) sysloop [-e|-f] -q [-p <pipe>]
+#
+#+Form (1) creates a pipe and runs a reader loop and (2) aditionally starts a ticker
+# (heartbeat) process. Form (3) sends a message and (4) terminates loop and ticker.
+#
+# Options:  -c      [*] a script function to process events
+#           -e      report failures as error messages
+#           -f      make errors fatal
+#           -m      [*] send a message
+#           -p      path of a fifo used as pipe (default: CEN_SYSLOOP[0])
+#           -q      [*] send quit message to terminate the read loop
+#           -t      start a heartbeat process (ticker)
+#
+#                   [*] These options are mutually exclusive
+#
+# Arguments:<evnt>      event handler function
+#           <mesg>      text to be sent (''<CR>'' chars changed to ''<TAB>'')
+#           <pipe>      path of fifo to be used. Created if needed
+#           <time>      heartbeat interval in [s]
+#           <tick>      heartbeat message (default is 'TICK')
+#
+#+Return:   **0** at success or **1** for error. A result code >= **2** is an
+#           error stop caused by the event handler that returned this code.
+#
+#+Each main process can only run one sysloop instance. The state is kept in:
+#
+#,          - CEN_SYSLOOP[0]    path of fifo
+#,          - CEN_SYSLOOP[1]    event handler function
+#,          - CEN_SYSLOOP[2]    pid of ticker
+#
+#+Form (1) and (2) will create a fifo as needed, without <pipe> a temporary
+# fifo path is used (see [[tmpfile()]]). Once opened the fifo path is saved in
+# CEN_SYSLOOP[0]. The sysloop function will never delete the file nor will
+# CEN_SYSLOOP[0] be unset. When option -c is used, sysloop will not return
+# before the event handler returns a status other than **0**.
+#
+#+Option -c registers the event handler an enters a read loop. The loop stops when
+# a quit message is received, see option -q. Stopping the event loop also kills
+# the ticker via CEN_SYSLOOP[2], clears CEN_SYSLOOP[1] and clears CEN_SYSLOOP[2].
+#
+#+Before starting a ticker, a quit hook is registered to make sure that the
+# ticker sub-shell gets terminated on [[quit()]]. For the lifetime of the ticker
+# a trap handler is registered, see [[context()]] options **-t°+** and  **-t°-**.
+#
+#+Events:   The event handler function is called with 2 or more arguments:
+#
+#,          $1      PID of the sender
+#,          $2      1st <mesg> argument from sender
+#,          ...     more <mesg> arguments from sender
+#
+#+          A return code of 1 will terminate the event loop (without error).
+#           Return codes >= 2 indicate error termination.
+#
+#.Example:  # event handler function
+#.          msgproc() {
+#.              local pid="$1" ; shift
+#.              message -p "Got %s arguments from PID=%s" $# "$pid"
+#.              return 0            # 0: continue  1: quit  2: error
+#.          }
+#.
+#.          # start event loop and a heartbeat process
+#.          sysloop -e -c msgproc -t 5 -- 'tick' || return
+#.          quit "success"
+#
+#.          # some other process may send events
+#.          sysloop -e -m -p "$pipe" -- 'hello world'
+#.          sysloop -e -m -q "$pipe"
+#
+#.          # it is possible to start/stop the ticker independently
+#.          sysloop -f -t 5 -p "$pipe" -s "$
+#.          kill "${CEN_SYSLOOP[2]}"
+# ------------------------------------------------------------------------------
+CEN_SYSLOOP=
+sysloop() {
+    #$CEN_DEBUG -c -- "$*"
+    local _emsg="$CEN_TRACE" _fatl _frun _isok _pipe _time
+    while [ "${1::1}" = "-" ] ; do
+      case "$1" in
+      --)   shift ; break ;;
+      -c)   shift ; isfunction -a -- "$1" ; _frun=1
+            CEN_SYSLOOP=("$CEN_SYSLOOP" "$1" "${CEN_SYSLOOP[2]}") ;;
+      -e)   _emsg='error' ;;
+      -f)   _emsg='fatal' ; _fatl='-f' ;;
+      -m)   _frun=2 ;;
+      -p)   shift ; _pipe="${1:--}" ; _isok=1 ;;
+      -q)   _frun=0 ;;
+      -t)   shift ; _time="$1" ; _isok=1 ;;
+      *)    _cen_abort - "$1"
+      esac ; shift
+    done
+
+    # get fifo
+    if [ -z "$CEN_SYSLOOP" -o -n "$_pipe" ] ; then
+        if [ "${_pipe:--}" = '-' ] ; then
+            tmpfile $_fatl -p -r -s _pipe || return 1
+        elif [ -p "$_pipe" ] ; then
+            :
+        elif [ ! -e "$_pipe" ] ; then
+            sysrun ${_fatl:--e} -r -- mkfifo -- "$_pipe" || return 1
+        else
+            $_emsg "Not a pipe:" "$_pipe" ; return 1
+        fi
+        prettypath -s CEN_SYSLOOP -- "$_pipe"
+    fi
+
+    # start ticker
+    if [ -n "$_time" ] ; then
+        if [[ "$_time" =~ ^[0-9]+(.[0-9]*)? ]] ; then
+            _cen_pip_ticker "$_time" "$1"
+        else
+            $_emsg "Invalid time:" "$_time" ; return 1
+        fi
+    fi
+
+    if [ "$_frun" = 0 ] ; then                  # sent quit ...
+        echo "$BASHPID" - > "$CEN_SYSLOOP" 2>/dev/null
+        trace -a "sysloop sent quit, status=" $?
+
+    elif [ "$_frun" = 1 ] ; then                # event loop ...
+        trace "sysloop enter loop (pipe=$CEN_SYSLOOP)"
+        local _epid _emsg _earg _ecnt _stat=0
+        while [ -n "${CEN_SYSLOOP[1]}" ] ; do
+           while read -r _epid _ecnt _emsg ; do
+                if [ -n "${_epid//[0-9]/}" -o -n "${_ecnt//[-0-9]/}" ] ; then
+                    trace "sysloop input ignored:" "$_epid" "$_ecnt"
+                    continue
+                elif [ "${_ecnt:--}" = '-' ] ; then
+                    trace -a -p "sysloop quit message from PID=%s" "$_epid"
+                    _stat=0 ; CEN_SYSLOOP[1]= ; break
+                elif [ "$_ecnt" -gt 1 ] ; then
+                    splitjoin -s _earg -d '\a' -- "$_emsg"
+                    ${CEN_SYSLOOP[1]} "$_epid" "${_earg[@]}" && continue
+                else
+                    ${CEN_SYSLOOP[1]} "$_epid" "$_emsg" && continue
+                fi
+                _stat=$? ; CEN_SYSLOOP[1]= ; break
+           done < "$CEN_SYSLOOP"
+        done
+        trace -p "sysloop exit loop (status %s)" "$_stat"
+        _cen_pip_ticker                         # stop ticker
+        [ "$_stat" -gt 1 ] && return $_stat
+
+    elif [ "$_frun" = 2 ] ; then                # sent message ...
+        local _mesg="$1"
+        [ $# -gt 1 ] && splitjoin -j _mesg -d '\a' -- "$@"
+        if echo "$BASHPID" $# "${_mesg//$'\n'/$'\t' }" > "$CEN_SYSLOOP" 2>/dev/null ; then
+            trace -a "sysloop send success:" "$BASHPID $*"
+        else
+            $_emsg "sysloop send failed:" "$BASHPID $*" ; return 1
+        fi
+
+    else
+        [ -z "$_isok" ] && _cen_abort + '-c|-m|-q|-t'
+    fi
+    return 0
+}
+
+# start or stop ticker: [<time> <mesg> [<ppid>]]
+#   no args: stop  two args: start  three args: run loop
+_cen_pip_ticker() {
+    if [ $# = 0 ] ; then
+        [ -z "${CEN_SYSLOOP[2]}" ] && return 1
+        kill "${CEN_SYSLOOP[2]}" 2>/dev/null && trace "sysloop ticker stopped"
+        CEN_SYSLOOP[2]=
+        context -t -
+        return 0
+    elif [ $# -lt 3 ] ; then
+        [ -n "${CEN_SYSLOOP[2]}" ] && return 1
+        if [ -z "$CEN_PIP_QUIT" ] ; then
+            CEN_PIP_QUIT="$CEN_HOOK_QUIT"
+            CEN_HOOK_QUIT=_cen_pip_quit
+        fi
+        context -t +
+        _cen_pip_ticker "$1" "${2:-TICK}" "$$" &
+        CEN_SYSLOOP[2]=$!
+        trace "sysloop ticker started (PID=$!):" "$1" "${2:-TICK}"
+        return 0
+    fi
+
+    # ticker loop, runs until signal
+    while sleep "$1" ; do
+        echo "$3 0 $2" > "$CEN_SYSLOOP" 2>/dev/null || return 1
+    done
+}
+
+# hook to terminate ticker process
+_cen_pip_quit() {
+    $CEN_NOTRACE set +x
+    sysbind -i '*' -t                       # stop all servers
+    _cen_pip_ticker                         # stop sysloop ticker
+    $CEN_NOTRACE set -x
+    $CEN_PIP_QUIT "$@"
+} || :
 
 # end
