Version 1.20 api level 2

diff --git a/library/_centauri_bash_pip b/library/_centauri_bash_pip
--- a/library/_centauri_bash_pip
+++ b/library/_centauri_bash_pip
@@ -262,7 +262,7 @@ syspager() {
 
     [ $# = 0 ] && return 0                  # nothing to run or no pager
     isfunction -e -x -- "$1" || return 1    # need function or command
-    if [ -z "$CEN_PAGER" ] ; then
+    if [ -z "$CEN_PAGER" -o -n "$CEN_SYSPIPE" ] ; then
         "$@" ; return
     fi || :
 
@@ -301,11 +301,16 @@ syspager() {
 # ------------------------------------------------------------------------------
 # syspipe - run a command in background using coproc or a pipe
 #
-# Call:     syspipe ORIGIN [DESTINATION] [-c <error>|-|+]
-#                   [-e|-f] [-g] [-n] [-r] [-v] [-x] [-y] -- <cmd> <arg>...
+# Call:     (1) syspipe -b <producer> -d <consumer>
+#                       [-c <error>|-|+] [-f] [-g] [-r] [-y] [--] <arg>...
+#           (2) syspipe -o <producer> -b <consumer>
+#                       [-c <error>|-|+] [-f] [-g] [-r] [-y] [--] <arg>...
 #
-#           ORIGIN      := -o <producer> | -i <var> | -i -
-#           DESTINATION := -d <consumer> | -a <array> | -s <string>
+#           (3) syspipe ORIGIN [DESTINATION] [-c <error>|-|+]
+#                       [-e|-f] [-g] [-n] [-r] [-v] [-x] [-y] [--] <cmd> <arg>...
+#
+#               ORIGIN      := -o <producer> | -i <var> | -i -
+#               DESTINATION := -d <consumer> | -a <array> | -s <string>
 #
 # Options:  -a  [*] put output into an array (overrides -c)
 #           -d  [*] destination script function (stdin -> <consumer>)
@@ -335,6 +340,13 @@ syspager() {
 #           [#] using external commands possibe but not recommended
 #
 # Return:   **true** at success or **false** otherwise.
+#
+#+Pipe:     Form (1) and (2) create a pipe. The option -b part runs in a background
+#           sub-shell whereas the -o or -d part runs in the caller's shell. So in (1)
+#           the <producer> runs in a sub-shell and in (2) the <consumer> runs in a
+#           sub-shell. Remember: a simple '<producer> | <consumer>' command would run
+#           both sides in a sub-shell. Any <arg>... parameters are passed to the
+#           <producer> and the <consumer>.
 #
 #+Coproc:   I/O redirection (and "|" pipes) run the command (or function) in a
 #           sub-shell. This makes it difficult to pass lengthy output back to
@@ -406,12 +418,13 @@ syspager() {
 CEN_SYSPIPE=
 syspipe() {
     #$CEN_DEBUG -c -- "$*"
-    local _fcop _fcap _fnoc _fqui \
-          _ocal='_cen_pip_error' _odst _oerr _ogra _omsg='error -z' _osrc _oinp _oout _orun
+    local _fbak _fcop _fcap _fnoc _fqui \
+          _ocal='_cen_pip_error' _ocon _odst _oerr _ogra _omsg='error -z' _osrc _oinp _oout _orun
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -a)   shift ; [ "$1" = '-' ] && _oout=2 || _oout=1 ; _ocon="splitjoin -s $1 -i - -l -n" ;;
+      -b)   shift ; _fbak="$1" ;;
       -c)   shift ; _ocal="$1" ;;
       -d)   shift ; _oout=0 ; _ocon="$1" ;;
       -e)   _oerr='-e' ;;
@@ -429,7 +442,15 @@ syspipe() {
       esac ; shift
     done
 
-    [ -z "$_osrc$_ocon" ] && _cen_abort + "-i|-o|-d|-a|-s"
+    if [ -n "$_fbak" ] ; then
+        _fnoc=1
+        [ "${_oout:-0}" = 0 ] || _cen_abort - '-a|-s'
+        [ -z "$_osrc$_oout" ] && _cen_abort + '-i|-o'
+        [ -n "$_osrc" -a -n "$_ocon" ] && _cen_abort ? '-i|-o'
+        [ -z "$_fcop$_oinp" ] || _cen_abort - '-i|-x'
+    elif [ -z "$_osrc$_ocon" ] ; then
+        _cen_abort + '-i|-o|-d|-a|-s'
+    fi
     CEN_SYSPIPE=                                # reset state
     local _stat=0 _verb="$CEN_VERB" _acmd=("$@") _cen_pip_temp
 
@@ -446,11 +467,11 @@ syspipe() {
         fi
     fi
 
-    # default error handler
+    # default error handler: (STATUS <code>) | (<info> -) <mesg>
     _cen_pip_error() {
         IFS=$' \n\t'                                    # repair IFS
         if [ "$1" = 'STATUS' ] ; then
-            [ "$_stat" -gt "${_ogra:-0}" ] &&
+            [ "$2" -gt "${_ogra:-0}" ] &&
                 $_omsg -p $"command failed (status %s): %s" "$2" "$3"
         else
             $_omsg -p $"command failed (%s): %s" "$1" "$3"
@@ -513,9 +534,11 @@ syspipe() {
                [ -n "$_fcap" ] && exec 2>&1
                shift
                if isfunction -- "$_acmd" ; then
+                    # disabled - trace -a -c ' ' "Call: $_acmd"
                     # a function may create subprocesses and temporary files
-                    "${_acmd[@]}" ; wait ; tmpfile -d
+                    "${_acmd[@]}" ; wait ; tmpfile -d ; return
                else
+                    # disabled - trace -a -c ' ' "Exec: $_acmd"
                     # exec is safe here as we are called as last cmd in subshell
                     exec "${_acmd[@]}"
                fi
@@ -525,6 +548,7 @@ syspipe() {
             if [ "$1" = '<>' ] ; then
                 tmpfile -r -s _pipe[1] -f ; CEN_SYSPIPE="${_pipe[*]}"
             fi
+            trace -a -c "() $1" "worker: $_acmd"
             [ "$_verb" -gt 1 ] && context -v 1          # disable debug output
 
             if [ "$1" = '<>' ] ; then
@@ -537,7 +561,19 @@ syspipe() {
         }
 
         local _pipe
-        if [ -n "$_osrc" ] ; then                       # has source function
+
+        # simple pipe with background subshell
+        if [ -n "$_fbak" ] ; then
+            _acmd=("$_fbak" "$@")
+            if [ -z "$_osrc" ] ; then
+                _cen_pip_worker '>' ; CEN_PIP_WAIT=$!
+                "$_ocon" "$@" < "$_pipe" || _cen_pip_error STATUS "$?" "$_ocon"
+            else
+                _cen_pip_worker '<' ; CEN_PIP_WAIT=$!
+                "$_osrc" "$@" > "$_pipe" || _cen_pip_error STATUS "$?" "$_osrc"
+            fi
+
+        elif [ -n "$_osrc" ] ; then                     # has source function
             if [ -n "$_ocon" ] ; then                   # ... and consumer
                 _cen_pip_worker '<>' ; CEN_PIP_WAIT=$!
             else                                        # ... only producer
@@ -717,16 +753,17 @@ sysloop() {
         $CEN_TRACE -a -c " sent quit" "status=$?"
 
     elif [ "$_frun" = 1 ] ; then                # event loop ...
-        $CEN_TRACE -c " enter loop" "pipe=$CEN_SYSLOOP"
+        $CEN_TRACE -c " loop" "pipe=$CEN_SYSLOOP"
         local _epid _emsg _earg _ecnt _stat=0
         CEN_SYSLOOP[3]="$_rpip"
         while [ -n "${CEN_SYSLOOP[1]}" ] ; do
-           while read -r _epid _ecnt _emsg ; do
+            _epid=                              # flag for read error
+            while read -r _epid _ecnt _emsg < "$CEN_SYSLOOP" ; do
                 if [ -n "${_epid//[0-9]/}" -o -n "${_ecnt//[-0-9]/}" ] ; then
-                    $CEN_TRACE -c " input ignored" -- "$_epid" "$_ecnt"
+                    $CEN_TRACE -c " ignored" -- "$_epid" "$_ecnt"
                     continue
                 elif [ "${_ecnt:--}" = '-' ] ; then
-                    $CEN_TRACE -a -c " quit msg." "from PID=$_epid"
+                    $CEN_TRACE -a -c " quit msg" "from PID=$_epid"
                     _stat=0 ; CEN_SYSLOOP[1]= ; break
                 elif [ "$_ecnt" -gt 1 ] ; then
                     splitjoin -s _earg -d '\a' -- "$_emsg"
@@ -734,10 +771,13 @@ sysloop() {
                 else
                     ${CEN_SYSLOOP[1]} "$_epid" "$_emsg" && continue
                 fi
-                _stat=$? ; CEN_SYSLOOP[1]= ; break
-           done < "$CEN_SYSLOOP"
+            done
+            if [ -z "$_epid" ] && [ ! -r "$CEN_SYSLOOP" ] ; then
+                error "Cannot read pipe:" "$CEN_SYSLOOP"
+                _stat=2 ; break
+            fi
         done
-        $CEN_TRACE -c " exit loop" "status=$_stat"
+        $CEN_TRACE -c " end loop" "status=$_stat"
         _cen_pip_ticker                         # stop ticker
         [ "$_stat" -gt 1 ] && return $_stat
 
@@ -745,9 +785,9 @@ sysloop() {
         local _mesg="$1"
         [ $# -gt 1 ] && splitjoin -j _mesg -d '\a' -- "$@"
         if echo "$BASHPID" $# "${_mesg//$'\n'/$'\t' }" > "$CEN_SYSLOOP" 2>/dev/null ; then
-            $CEN_TRACE -a -c " send success" -- "$BASHPID $*"
+            $CEN_TRACE -a -c " send OK" -- "$BASHPID $*"
         else
-            $_emsg -c " send failed" -- "$BASHPID $*" ; return 1
+            $_emsg -c " send err" -- "$BASHPID $*" ; return 1
         fi
 
     else
diff --git a/library/_centauri_bash_utl b/library/_centauri_bash_utl
--- a/library/_centauri_bash_utl
+++ b/library/_centauri_bash_utl
@@ -112,8 +112,10 @@ listsearch() {
 # optmake - Build options string or array
 #
 # Call:     optmake -s|-j|-a <dest> [-k|-n <name>] [-f|-v|-z] <valu>
+#           optmake -s|-j|-a <dest> -b <opti>
 #
 # Options:  -a  add result to <dest> array
+#           -b  copy a builitin option
 #           -f  option is a flag, no value
 #           -j  add result to <dest> variable
 #           -k  key name (not an option)
@@ -125,6 +127,7 @@ listsearch() {
 #
 #.Examples: optmake -a opts -v "$CEN_OPT_INPUT"                 # argument
 #.          optmake -a opts -- "-version"                       # constant
+#.          optmake -a opts -b pager                            # builtin
 #.          optmake -s opts -n host -m -v "$CEN_OPT_HOST"       # text value
 #.          optmake -j opts -n logical -f "$CEN_OPT_LOGICAL"    # flag
 #.          optmake -a opts -n number  -z "$CEN_OPT_NUMBER"     # num. value
@@ -132,6 +135,7 @@ listsearch() {
 #
 #.          optmake -j args        -v "$addr"       # add a value
 #.          optmake -j args -k mtu -v "$vmtu"       # add key/value
+#.          optmake -j args -b verb                 # add builtin --verbose
 #
 #+If the option <name> starts with '-' or '--' the generated code for
 # string output (option -j or -s) is:
@@ -143,13 +147,19 @@ listsearch() {
 #+When used with -a option optmake never generates a '=' separator but
 # puts the <valu> into an extra array element. For string output only
 # simple quoting is used, e.g. '''"''' in <valu> are changed to '''\"'''.
+#
+#+For builitin options (-b) the following <opti> values are recognized:
+#
+#,      dryrun|force|silent|trace|quiet|zombie
+#,      gui|pager|verb*|yesno
 # ------------------------------------------------------------------------------
 optmake() {
-    local _vset _name _vflg _asep _fmin _valu
+    local _vset _name _vflg _asep _blti _fmin _valu
     while [ "${1::1}" = "-" ] ; do
       case "$1" in
       --)   shift ; break ;;
       -a)   shift ; _vset="a" ; local -n _vvaa="$1" ;;
+      -b)   shift ; _blti="$1" ;;
       -f)   shift ; _valu="$1" ; _vflg=0 ;;
       -m)   shift ; _fmns=1 ;;
       -j)   shift ; _vset="j" ; local -n _vvaa="$1" ;;
@@ -165,11 +175,28 @@ optmake() {
     if [ -z "$_vflg" ] ; then                   # no -f|-v|-z option
         _valu="$1" ; _vflg=0
     fi
-    case "$_valu" in
-        "") return ;;
-        -)  [ -z "$_fmns" ] && return ;;
-        0)  [ "$_vflg" = 2 ] && return ;;
-    esac
+    if [ -n "$_blti" ] ; then                   # builtin options
+        [ -n "$_name" ] && _cen_abort - '-b|-n|-k'
+        _name="$_blti" ; _vflg=0
+        eval _valu="\$CEN_OPT_${_name^^}"
+        case "$_blti" in
+        dryrun|force|silent|trace|quiet|zombie)
+                    [ -z "$_valu" ] && return ;;
+        gui)        [ "$_valu" = 2 ] && return
+                    _vflg=1 ;;
+        pager)      _vflg=1 ;;
+        verb*)      [ "$CEN_VERB" -le 1 ] && return ;;
+        yesno)      [ -z "$CEN_YESNO" ] && return
+                    [ "$CEN_YESNO" = 'y' ] && _name='yes' || _name='no' ;;
+        *)          _cen_abort $"unknown option:" "$_blti"
+        esac
+    else
+        case "$_valu" in
+            "") return ;;
+            -)  [ -z "$_fmns" ] && return ;;
+            0)  [ "$_vflg" = 2 ] && return ;;
+        esac
+    fi
 
     case "$_name" in
     "")         ;;
@@ -555,8 +582,8 @@ _cen_scal_wait() {
 # ------------------------------------------------------------------------------
 # timer - sleep, return elapsed time, run poll loop
 #
-# Call:     (1) timer -a                         # implies -t -p -
-#               timer [-a] -t|-m                 # implies -p -
+# Call:     (1) timer [-a] -m                    # show elapsed time via message
+#               timer [-a] -t                    # show elapsed time via trace
 #               timer [-a] -t|-m -p <pfmt>       # explicit printf format
 #               timer <opts> [--] <text>...      # append text to output
 #           (2) timer -s <vnam>                  # save current epoch time
@@ -602,7 +629,7 @@ _cen_scal_wait() {
 #+Polling:  With option -l the callback function is called in a loop until it
 #           returns 0 (ready, exit code 0), or a <stat> > 1 (stop, exit code <stat>).
 #           A return code of 1 continues polling. When <wait> has expired <func>
-#           is called for a last time with option -l, and the return values becomes
+#           is called for a last time with option -e, and the return values becomes
 #           the timer exit code.
 #
 #+          The two non-option arguments of <func> are elapsed time and total wait
@@ -619,10 +646,10 @@ _cen_scal_wait() {
 #.          local curr; timer -s curr
 #.          do_something one  ; timer -a -p "%s [ms]: do_something" -t -i - -- one
 #.          do_something two  ; timer -a -p "%s [ms]: do_something" -t -i - -- two
-#.          timer -i "$curr" ; time -p "Total elapsed time: %s [ms]"
+#.          timer -i "$curr" ; timer -p "Total elapsed time: %s [ms]"
 #
 #.          # run a poll loop
-#.          poll_func() {  [ "$1" = '-l' ] || return 0 ; [ -e "flagfile" ] }
+#.          poll_func() {  [ "$1" = '-l' ] || return 0 ; [ -e "flagfile" ] ; }
 #.          timer -w 10 -l 200 -c poll_func -h || quit "Timeout"
 #.          timer -s mesg -p "% [ms]"
 #.          message "Ready after" "$mesg" " wait time."
@@ -747,6 +774,10 @@ timer() {
 #           -t  don't trim leading
 #           -s  use <name> to save result (default is CEN_TRIMJOIN)
 #           -w  simplify whitespace (<TAB>, <CR> and <LF> are whitspace)
+#
+# Arguments:<maxl>  max. columns or '+' for max. width or '-' for indentation
+#           <name>  variable name
+#           <text>  text to process
 #
 #.Examples: trimjoin -- "  hi  "                    # trim into CEN_TRIMJOIN
 #.          trimjoin -a -- "there"                  # append
