Minor fixes, optarg -v, invoke -i

diff --git a/library/_centauri_bash_net b/library/_centauri_bash_net
--- a/library/_centauri_bash_net
+++ b/library/_centauri_bash_net
@@ -45,9 +45,14 @@ CEN_NET_FILE_PROX="$CEN_NET_DIR_RUN/network_proxy"
 
 CEN_NET_PREFIX_IP6_DFLT='fc01::/96'
 
+# data for netiface ...
+
 CEN_NET_IFNAMES=                # 0:=no mapping  1:=systemd names
 CEN_NET_IFMAP=                  # list of interface mappings
 CEN_NET_IFKCMD=                 # flag for net.ifnames
+CEN_NET_IFIEN=0                 # ethernet index
+CEN_NET_IFIWL=0                 # wlan ...
+CEN_NET_IFIUS=0                 # usb ...
 
 # ------------------------------------------------------------------------------
 # Interface Naming + About BIOS, systemd and internal interface names
@@ -514,10 +519,14 @@ netiface() {
     if [ -n "$_ncmd" ] ; then               # get cmdline status only
         _cen_net_getkcmd ; return
     fi
-    [ -z "$CEN_NET_IFNAMES" ] && _cen_net_mapinit
-
+    if [ -z "$CEN_NET_IFNAMES" ] ; then
+        _cen_net_mappers -r
+        if [ -z "$CEN_NET_IFNAMES" ] ; then
+            _cen_net_mapinit ; _pers=1
+        fi
+    fi
     if [ -n "$_pers" ] ; then               # create mapping file
-        _cen_abort - $"option -p not implemented"
+        _cen_net_mappers -w || return 1
     fi
 
     # only ethernet and wlan names are mapped
@@ -574,26 +583,85 @@ _cen_net_getkcmd() {
     return "$CEN_NET_IFKCMD"
 }
 
+_cen_net_maptest() {
+    local _vote=1 _name
+    while [ $# -gt 0 ] ; do
+        _name="$1" ; shift
+        [ -e "$_name" ] || continue
+        case "${_name##*/}" in
+        en?p?)  ((_vote += 1)) ;;
+        wl?p?)  ((_vote += 1)) ;;
+        end?)   ((_vote += 1)) ;;
+        eth?)   ((_vote -= 1)) ;;
+        wlan?)  ((_vote -= 1)) ;;
+        esac
+    done
+    $CEN_TRACE2 -a -c "interface votes" "$_vote"
+    [ "$_vote" -le 0 ]                              # return status
+}
+
 # get current map mode, set CEN_NET_IFNAMES, load rules
 _cen_net_mapinit()  {
     [ -z "$CEN_NET_DOMAIN" ] && { netconfig || return 1 ; }
     [ -n "$CEN_NET_IFNAMES" ] && return
 
-    # check for kernel net.ifnames
-    _cen_net_getkcmd && CEN_NET_IFNAMES=0 || CEN_NET_IFNAMES=1
-    # must use some heuristics as initrd might be out of sync
-    if [ "$CEN_NET_IFNAMES" = 1 ] ; then
-        if [ -e '/sys/class/net/eth0' ] || [ -e '/sys/class/net/wlan0' ] ; then
-            CEN_NET_IFNAMES=0
-        elif [ '/etc/systemd/network/99-default.link' -ef '/dev/null' ] ; then
-            CEN_NET_IFNAMES=0
-        fi
+    # check for kernel net.ifnames, then try some heuristics
+    if _cen_net_getkcmd ; then                      # this is mandatory
+        CEN_NET_IFNAMES=0
+    elif _cen_net_maptest "/sys/class/net/"[ew]* ; then
+        CEN_NET_IFNAMES=0
+    else
+        CEN_NET_IFNAMES=1
     fi
     if [ "$CEN_NET_IFNAMES" = 0 ] ; then
         $CEN_TRACE -a -c "interface names" 'bios'
     else
         [ -n "$CEN_NET_IFACES" ] && _cen_net_maprule    # iface rules
         $CEN_TRACE -a -c "interface names" 'systemd'
+
+        local _item _more=()
+        for _item in /sys/class/net/en* ; do
+            case "${_item##*/}" in
+            *u?)    [ -e "$_item" ] && _cen_net_mapiadd 'usb' "${_item##*/}" ;;
+            end?)   [ -e "$_item" ] && _cen_net_mapiadd 'eth' "${_item##*/}" ;;
+            *)      [ -e "$_item" ] && _more+=("$_item")
+            esac
+        done
+        for _item in "${_more[@]}" ; do
+            case "${_item##*/}" in
+            enp?s?) _cen_net_mapiadd 'eth' "${_item##*/}"
+            esac
+        done
+        for _item in "${_more[@]}" ; do
+            case "${_item##*/}" in
+            enp?s?) ;;
+            *)      _cen_net_mapiadd 'eth' "${_item##*/}"
+            esac
+        done
+        for _item in /sys/class/net/wlp* /sys/class/net/wl[!p]* ; do
+            [ -e "$_item" ] && _cen_net_mapiadd 'wlan' "${_item##*/}"
+        done
+    fi
+}
+
+# handle persistancy: -r|-w
+_cen_net_mappers()  {
+    if [ "$1" = '-w' ] ; then
+        if [ "$EUID" != 0 ] ; then
+            CEN_TRACE2 "ifnames not persisted for non-root user"
+            return 0
+        fi
+        local _imap="${CEN_NET_IFMAP[@]@A}" ; _imap="${_imap#declare -* }"
+        nettemp -w 'network_ifnames' <<!EOF
+${CEN_NET_IFKCMD@A}
+${CEN_NET_IFNAMES@A}
+$_imap
+${CEN_NET_IFIEN@A}
+${CEN_NET_IFIWL@A}
+${CEN_NET_IFIUS@A}
+!EOF
+    else
+        _cen_source "$CEN_NET_DIR_RUN/network_ifnames" ; return
     fi
 }
 
@@ -623,15 +691,17 @@ _cen_net_mapping() {
         case "$_mapn" in
         enx*)   _cen_net_mapbios "$_mapn" /sys/class/net/enx* ;;
         end*)   _cen_net_mapbios "$_mapn" /sys/class/net/end* ;;
+        enp*u?) _cen_net_mapbios "$_mapn" /sys/class/net/enp*u? ;;
         en*)    _cen_net_mapbios "$_mapn" /sys/class/net/enp* /sys/class/net/en[!p]* ;;
         wl*)    _cen_net_mapbios "$_mapn" /sys/class/net/wlp* /sys/class/net/wl[!p]* ;;
         esac
     elif [ "$1" = '-s' ] ; then             # map to systemd
         case "$_mapn" in
-        eth*)   _cen_net_mapsysd "$_mapn" /sys/class/net/enp* /sys/class/net/en[!p]* ;;
-        usb*)   _cen_net_mapsysd "$_mapn" /sys/class/net/enx* ;;
         wlan*)  _cen_net_mapsysd "$_mapn" /sys/class/net/wlp* /sys/class/net/wl[!p]* ;;
+        usb*)   _cen_net_mapsysd "$_mapn" /sys/class/net/enp*u? ;;
+        *)      _cen_net_mapsysd "$_mapn" /sys/class/net/enp* /sys/class/net/en[!p]* ;;
         esac
+        _cen_net_mapsysd "$_mapn"
     fi
     printf -v "$_vnam" '%s' "$_netiface_mapname" ; return 0
 }
@@ -648,58 +718,74 @@ _cen_net_maprule() {
             warning -c $"not implemented" -- "iface $_item"
             continue
         fi
-        _cen_net_mapiadd "$1=$3" ; _cen_net_mapiadd "$3=$1"
+        _cen_net_mapiadd "$1" "$3"
     done ; set +f
     $CEN_TRACE -a -c "mapping iface" -- "${#CEN_NET_IFMAP[@]} rule(s)"
 }
 
-# map to bios name
+# map to bios name: <sysd> <candidate>...
 _netiface_mapname=
 _cen_net_mapbios() {
     local _mapn="$1" _item _bios _indx=0 _kern _kind='eth'
     [ "${_mapn::2}" = 'wl' ] && _kind='wlan'
     $CEN_TRACE2 -a -c "mapping bios" -- "$*"
 
-    # loop over interface and add bios name to cache
+    # loop over interfaces and add bios name to cache
     while [ $# -gt 1 ] ; do
         shift
         [ -e "$1" ] || continue
         _kern="${1##*/}"
-        _bios="$_kind$_indx" ; ((_indx += 1))   # make bios name
-        _cen_net_mapiadd "$_kern=$_bios"
-        if [ "$_kern" = "$_mapn" ] ; then       # stop on name match
-            _netiface_mapname="$_bios" ; return
-        fi
+        _cen_net_mapiadd "$_mapn" "$_kern" _netiface_mapname && return
     done
+    _netiface_mapname=
 }
 
-# map to systemd name
+# map to systemd name: <bios> <candidate>...
 _cen_net_mapsysd() {
     $CEN_TRACE2 -a -c "mapping systemd" -- "$*"
     local _mapn="$1" _item _kern
+
     while [ $# -gt 1 ] ; do
         shift
         [ -e "$1" ] || continue
         _kern="${1##*/}"
-
-        # skip interfaces that are already registered
-        for _item in "${CEN_NET_IFMAP[@]}" ; do
-            [ "${_item#*=}" = "$_kern" ] || continue
-            $CEN_TRACE2 -a -c "mapping skipped" -- "$_item" ; _kern= ; break
-        done
-        [ -z "$_kern" ] && continue
-        _netiface_mapname="${1##*/}"
-        _cen_net_mapiadd "$_mapn=$_netiface_mapname" ; return
+        if _cen_net_mapiadd "$_mapn" "$_kern" ; then
+            _netiface_mapname="$kern" ; return
+        fi
     done
+
+    # interface not registered
+    [ -e "$_mapn" ] && _netiface_mapname="$_mapn" : _netiface_mapname=
 }
 
-# add to list of known interfaces: <item>
+# Add to list of known interfaces: <bios> <sysd> [<vbio>]
+# This function always makes two entries:  <bios>=<sysd>  and  <sysd>=<bios>
 _cen_net_mapiadd() {
-    for _item in "${CEN_NET_IFMAP[@]}" ; do
-        [ "$_item" = "$1" ] && return
+    local _bios="$1" _sysd="$2" _entr _incr
+    case "$_bios" in
+    eth)    _bios+="$CEN_NET_IFIEN" ; _incr=1 ;;
+    wlan)   _bios+="$CEN_NET_IFIWL" ; _incr=2 ;;
+    en*)    _bios="eth$CEN_NET_IFIEN" ; _incr=1 ;;
+    wl*)    _bios="wlan$CEN_NET_IFIWL" ; _incr=2 ;;
+    us*)    _bios="usb$CEN_NET_IFIUS" ; _incr=3 ;;
+    esac
+    [ -n "$3" ] && printf -v "$3" '%s' "$_bios"
+
+    for _entr in "${CEN_NET_IFMAP[@]}" ; do
+        _entr="${_entr%=*}"
+        [ "$_entr" = "$_bios" ] && return 1
+        [ "$_entr" = "$_sysd" ] && return 1
     done
-    $CEN_TRACE -a -c "mapping added" -- "$1"
-    CEN_NET_IFMAP+=("$1")
+
+    if [ "$_incr" = 1 ] ; then                  # increment next index
+        ((CEN_NET_IFIEN += 1))
+    elif [ "$_incr" = 2 ] ; then
+        ((CEN_NET_IFIWL += 1))
+    elif [ "$_incr" = 3 ] ; then
+        ((CEN_NET_IFIUSS += 1))
+    fi
+    $CEN_TRACE -a -c "mappings added" -- "$_bios" "$_sysd"
+    CEN_NET_IFMAP+=("$_bios=$_sysd" "$_sysd=$_bios") ; return 0
 }
 
 # ------------------------------------------------------------------------------
@@ -1557,6 +1643,14 @@ _cen_net_homedns() {
 #
 #           [*] Form (2) calls can have a <host> argement. If missing HOSTNAME is used.
 #
+#+The result for uppercase keywords is based on the dynamic CEN_NET_ROLE, and
+# **NOT** the static configuration data. Lowercase keywords return static data.
+#
+#+The function calls [[netserver()]] if CEN_NET_ROLE is not yet set. To refresh
+# the loaded information, [[netserver()]] must be called explicitly. It always
+# calls [[netconfig()]]. So after a call to [[netquery()]] all CEN_NET_XXX state
+# and configuration variables are set.
+#
 #+connect:  depending on centaurinetcfg option settings one of the following is returned:
 #
 #           manual        not managed by centaurinetcfg/centauriswitch
@@ -1597,14 +1691,6 @@ _cen_net_homedns() {
 #.          else
 #.              message "Stand alone, server:" "${snam:-<none>}"
 #.          fi
-#
-#+The result for uppercase keywords is based on the dynamic CEN_NET_ROLE, and
-# **NOT** the static configuration data. Lowercase keywords return static data.
-#
-#+The function calls [[netserver()]] if CEN_NET_ROLE is not yet set. To refresh
-# the loaded information, [[netserver()]] must be called explicitly. It always
-# calls [[netconfig()]]. So after a call to [[netquery()]] all CEN_NET_XXX state
-# and configuration variables are set.
 # ------------------------------------------------------------------------------
 netquery() {
     local _ferr _ssav _valu _stat=1 _qual
@@ -1663,7 +1749,8 @@ netquery() {
 
     homedns)        if _cen_net_homedns _valu ; then
                         _stat=0
-                        _valu="${_valu%$_qual}"
+                        # (1) remove our own domain name (2) never qualify localhost
+                        [ "${_valu#*.}" = "$CEN_NET_DOMAIN" ] && _valu="${_valu%%.*}"
                         [ "$_valu" = 'localhost' ] && _qual=
                     fi ;;
 
@@ -1685,24 +1772,19 @@ netquery() {
     class)          [ "${2:--}" = '-' ] && set -- "$1" "$HOSTNAME"
                     if [ "$2" = "${CEN_NET_SERVERS[0]}" -o \
                          "$2" = "${CEN_NET_SERVERS[1]}" -o \
-                         "$2" = "$CEN_NET_SERVER_GEN" ] ; then
-                        _valu='server'
-                    elif netoption 'mobile' "$2" ; then
-                        _valu='mobile'
-                    elif netoption 'phone' "$2" ; then
-                        _valu='phone'
-                    elif netoption 'generic' "$2" ; then
-                        _valu='generic'
-                    elif nethost "$2" ; then
-                        _valu='client'
-                    else
-                        _valu='generic'
+                         "$2" = "$CEN_NET_SERVER_GEN" ]
+                    then                                    _valu='server'
+                    elif netoption 'mobile'  "$2" ; then    _valu='mobile'
+                    elif netoption 'phone'   "$2" ; then    _valu='phone'
+                    elif netoption 'generic' "$2" ; then    _valu='generic'
+                    elif nethost "$2" ; then                _valu='client'
+                    else                                    _valu='generic'
                     fi
-                    _qual=
+                    _qual= ; _stat=0
                     ;;
-
-    config)         _valu="${CEN_NET_CONFIG:-${CEN_NET_DOMAIN%%.*}}" ; _qual= ;;
-
+    config)         _valu="${CEN_NET_CONFIG:-${CEN_NET_DOMAIN%%.*}}"
+                    _qual= ; _stat=0
+                    ;;
     *)              _cen_abort - "$*"
     esac
 
@@ -2008,7 +2090,11 @@ nettool() {
                 [ "$_cmnd" = 'isu' ] && return 1
                 [ "$_cmnd" = 'dow' ] && return 0
                 [ "$_cmnd" = 'exi' ] && return 0
-                _tool='ifup' ; set -- '--force' "$_ifce"
+                if sysrun -q ifquery "$_ifce" ; then            # managed by ifup ...
+                    _tool='ifup' ; set -- '--force' "$_ifce"
+                else
+                    _tool='ip' ; set -- link set up "$_ifce"
+                fi
             fi
         fi
     fi
diff --git a/library/_centauri_bash_run b/library/_centauri_bash_run
--- a/library/_centauri_bash_run
+++ b/library/_centauri_bash_run
@@ -118,7 +118,7 @@ CEN_TERMINAL_DAT=
 #.  °   kiosk:qml           @launcher_qmlweb  1000 800 1.2
 #.  °   httpd:lighttpd      @launcher_httpd 8080 /var/www
 #.
-#.  °   # command line args
+#.  °   # command line arguments for external applications
 #.  °   kiosk:firefox       --fullscreen --new-window
 #.  °   browser:firefox     --new-window
 #.
@@ -202,7 +202,7 @@ CEN_TERMINAL_DAT=
 #
 #+General:  The [[launcher()]] function reads the (cached) configuration statements
 #           from section **[launcher]** in file "centauri-bash-lib". The preferred
-#           location of this file in "$CEN_ROOT/default", see [[configfile()]] for
+#           location of this file is "$CEN_ROOT/default", see [[configfile()]] for
 #           more details.
 #
 #+Config:   Valid "centauri-bash-lib" configuration lines are:
@@ -211,7 +211,7 @@ CEN_TERMINAL_DAT=
 #           °°<what>             § <desk> @<func>|<tool>...
 #           # set options and arguments of a command to be run
 #           °°<what>**:**<tool>  § <arg>...
-#           # command is run by a function
+#           # command is run by a user defined function
 #           °°<what>**:**<tool>  § @<func> <arg>...
 #           # optional: command not found if sym-linked to <nogo>
 #           °°**-ignore:**<tool> § <nogo>
@@ -251,17 +251,17 @@ CEN_TERMINAL_DAT=
 #.  °           browser:qml         @launcher_qmlweb 1024 768 1.2
 #.  °           kiosk:qml           @launcher_qmlweb 1000 800 1.2
 #.
-#.  °           # command line args
+#.  °           # command line arguments for external applications
 #.  °           kiosk:firefox       --fullscreen --new-window
 #.  °           browser:firefox     --new-window
 #.  °           kiosk:falkon        --fullscreen --new-window --no-extensions
 #.  °           browser:falkon      --new-window --no-extensions
 #.
 #.  °           # info text for generic names (not commands)
-#.  °           info:editor         text editor
-#.  °           info:browser        web browser
-#.  °           info:kiosk          web browser in kiosk mode
-#.  °           info:terminal       terminal emulator
+#.  °           -info:editor        text editor
+#.  °           -info:browser       web browser
+#.  °           -info:kiosk         web browser in kiosk mode
+#.  °           -info:terminal      terminal emulator
 # ------------------------------------------------------------------------------
 
 # ------------------------------------------------------------------------------
@@ -269,7 +269,11 @@ CEN_TERMINAL_DAT=
 #
 # Call:     <func> <option>.. -- <arg>...
 #
-# Options:  -f  error are fatal
+#           The purpose of the argument function <func> is to handle configuration
+#           options (see below) and to run a command. The command must be known
+#           by <func>. All <arg> arguments are user defined and optional.
+#
+# Options:  -f  errors are fatal
 #           -i  information string
 #           -m  lauch per exec or in background
 #           -o  override desktop status (force running emulator)
@@ -300,12 +304,12 @@ CEN_TERMINAL_DAT=
 #.                  esac ; shift
 #.              done
 #.
-#.              # option -x: check if executable and return status
+#.              # option -x: check if 'my-command' can be run and return status
 #.              if [ -n "$ochk" ] ; then
 #.                  sysfind -q -c -- 'my-command' || return 1
 #.              # run the command
 #.              else
-#.                  system $oeff $orun -- 'my-command' --tile "$otit" "$@" || return 1
+#.                  system $oeff $orun -- 'my-command' --title "$otit" "$@" || return 1
 #.              fi
 #.              return 0
 #.          }
@@ -322,6 +326,7 @@ CEN_TERMINAL_DAT=
 # Options:  -a  array of resulting command words (default is CEN_LAUNCHER)
 #           -f  errors are fatal
 #           -i  information string passed to callback
+#           -k  get configuration entry by key
 #           -l  [*] get application list
 #           -m  launch via exec or in background
 #           -n  [*] do not run, return command array
@@ -348,8 +353,8 @@ CEN_TERMINAL_DAT=
 # section "[launcher]", see [[launcher config]].
 #
 #+If the launcher configuration calls an argument function or a command function,
-# the final call passes options -f -i -m -q -r -t and -y to the function, see
-# [[launcher (callback)]].
+# the final call passes options -f -i -m -q -r -t and -y to that function, see
+# [[launcher°(callback)]].
 #
 # Form (1) searches a matching command and runs it. Form (2) does not run the
 # command, but returns the command (as an array of words). The configuration
@@ -385,8 +390,8 @@ CEN_TERMINAL_DAT=
 CEN_LAUNCHER=
 launcher() {
     $CEN_DEBUG -c -- "$*"
-    local _flst _oerr='-e' _ofun='-e' _onot _odsk _orun=() _temp
-    local _desk="${CEN_DESKTOP:-tty}" _warn="_cen_run_config -m launcher" _vnam='CEN_LAUNCHER'
+    local _flst _oerr='-e' _ofun='-e' _okey _onot _odsk _orun=() _temp
+    local _desk="${CEN_DESKTOP:-tty}" _warn='_cen_run_config -m launcher' _vnam='CEN_LAUNCHER'
 
     # do we have an -x option?
     for _temp in "$@" ; do
@@ -403,6 +408,7 @@ launcher() {
         -f)   _oerr='-f' ; _ofun='-f' ;;
         -i|-t)
               _orun+=("$1" "$2") ; shift ;;
+        -k)   shift ; _okey="${1:--}" ;;
         -l)   shift ; _flst="$1" ;;
         -m)   shift ; _orun+=('-m' "${1:-0}") ;;
         -n)   _onot=1  ;;
@@ -418,7 +424,7 @@ launcher() {
     # fetch configuration for [launcher]
     local _what="$1" _apps _line _larr _name _path _igno _fltr
     local -A _pard
-    $CEN_TRACE2 -c " parsing" -- "${_what:--} (mode=$_desk)"
+    $CEN_TRACE2 -c ' parsing' -- "${_what:--} (mode=$_desk)"
     _cen_run_config $_oerr 'launcher' || return 1
 
     # generic-name filtering if not listing
@@ -457,7 +463,11 @@ launcher() {
 
             -info:*)
                 [ -n "$_flst" ] && _pard["$_larr"]="${_larr[*]:1}" ;;
-            -flags:*|-ignore:*)
+            -flags:*)
+                _line="${_pard["$_larr"]}" ;
+                [ -n "$_line" ] && _pard["$_larr"]+=$'\n'
+                _pard["$_larr"]+="${_larr[*]:1}" ;;
+            -ignore:*)
                 _pard["$_larr"]="${_larr[*]:1}" ;;
 
             # In _cen_run_tools these strings are expanded by globbing. This can be
@@ -500,6 +510,13 @@ launcher() {
         esac
     done
 
+    # --- return a key ---
+
+    if [ -n "$_okey" ] ; then
+        splitjoin -s _vres -- "${_pard["$_okey"]}";
+        [ -n "$_vres" ] ; return                        # return status
+    fi
+
     # --- return a command list or find command ---
 
     local _fldr="$PWD" ; folder -c -f "${CEN_PATHS:-/}"
@@ -519,7 +536,7 @@ launcher() {
                     _vres+=("$_name"$'\a'"$_fltr"$'\a'"$_temp"$'\a'"${CEN_RUN_TOOLS[2]}")
             esac
         else
-            $CEN_TRACE2 -c -p " tool" "%-18s    NO MATCH" "$_line"
+            $CEN_TRACE2 -c -p ' tool' "%-18s    NO MATCH" "$_line"
             if [ -z "$_flst" ] ; then
                 folder -c -f "$_fldr"
                 return 1
@@ -532,7 +549,7 @@ launcher() {
     # --- run a command ---
 
     if [ -z "$_name" ] ; then
-        $CEN_TRACE -c " miss" -- "$_what" ; return 1
+        $CEN_TRACE -c ' miss' -- "$_what" ; return 1
     fi
 
     # split and unquote arguments via eval
@@ -541,21 +558,20 @@ launcher() {
         _vres=($_temp)
         $_warn $"Syntax error:" "$_temp"
     fi
-
     if [ "${_temp::1}" = '@' ] ; then           # argument function
         _vres=("${_temp%% *}" "${CEN_RUN_TOOLS[1]}" "${_vres[@]:1}" "${@:2}")
     else                                        # command or function
         _vres=("${CEN_RUN_TOOLS[1]}" "${_vres[@]}" "${@:2}")
     fi
 
-    $CEN_TRACE2 -c " exec" -- "$_name  =>  ${_vres[*]}"
+    $CEN_TRACE2 -c ' exec' -- "$_name  =>  ${_vres[*]}"
     [ -n "$_onot" ] && return 0
     _cen_run_command  $_oerr "${_orun[@]}" $_odsk -- "${_vres[@]}" || return $?
     return 0
 }
 
 # check if tool can be run: <list> <tool> <name>...    (using variable _pard)
-CEN_RUN_TOOLS=()                # (<tool> <path>)
+CEN_RUN_TOOLS=()                # (<tool> <path>|- ...)
 _cen_run_tools() {
     local _list="$1" _tool="$2" _name _path _igno _want _args _nice
     shift ; shift
@@ -579,7 +595,7 @@ _cen_run_tools() {
         [ "$_path" = '-' ] && return 1                      # negative cache entry
 
         if [ -n "$_path" ] ; then
-            $CEN_TRACE2 -a -c -p " CACHED" "%-18s => %s" "$_nice" "$_path"
+            $CEN_TRACE2 -a -c -p ' CACHED' '%-18s => %s' "$_nice" "$_path"
             CEN_RUN_TOOLS=("$_nice" "$_path" "$_args") ; return 0
         fi
 
@@ -593,7 +609,7 @@ _cen_run_tools() {
         if [ -n "$_igno" ] ; then                           # symlink ignore ...
             resolve -s _want -c -- "$_path"
             if [ "$_igno" = "${_want##*/}" ] ; then
-                $CEN_TRACE2 -c -p " IGNORE" "%-18s => %s" "$_nice" "$_path"
+                $CEN_TRACE2 -c -p ' IGNORE' '%-18s => %s' "$_nice" "$_path"
                 continue
             fi
         fi
@@ -603,11 +619,11 @@ _cen_run_tools() {
             for _want in $_want "" ; do
                 [ -e "$_want" ] && break
             done
-            $CEN_TRACE2 -c -p " WANTS" "%-18s => %s" "$_nice" "${_want:--miss-}"
+            $CEN_TRACE2 -c -p ' WANTS' '%-18s => %s' "$_nice" "${_want:--miss-}"
             [ -z "$_want" ] && continue
         fi
 
-        $CEN_TRACE2 -a -c -p " FOUND" "%-18s => %s" "$_nice" "$_path"
+        $CEN_TRACE2 -a -c -p ' FOUND' "%-18s => %s" "$_nice" "$_path"
         CEN_RUN_TOOLS=("$_nice" "$_path" "$_args")
         _pard[$_nice/]="$_path" ; return 0
     done
